"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SupplyChain202309ConfirmPackageShipmentResponseDataErrors = void 0;
class SupplyChain202309ConfirmPackageShipmentResponseDataErrors {
    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentResponseDataErrors.attributeTypeMap;
    }
}
exports.SupplyChain202309ConfirmPackageShipmentResponseDataErrors = SupplyChain202309ConfirmPackageShipmentResponseDataErrors;
SupplyChain202309ConfirmPackageShipmentResponseDataErrors.discriminator = undefined;
SupplyChain202309ConfirmPackageShipmentResponseDataErrors.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "detail",
        "baseName": "detail",
        "type": "SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ29uZmlybVBhY2thZ2VTaGlwbWVudFJlc3BvbnNlRGF0YUVycm9ycy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNvbmZpcm1QYWNrYWdlU2hpcG1lbnRSZXNwb25zZURhdGFFcnJvcnMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEseURBQXlEO0lBOEJsRSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8seURBQXlELENBQUMsZ0JBQWdCLENBQUM7SUFDdEYsQ0FBQzs7QUFoQ0wsOEhBaUNDO0FBdEJVLHVFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywwRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsaUVBQWlFO0tBQzVFO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsU0FBUztRQUNqQixVQUFVLEVBQUUsU0FBUztRQUNyQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==