"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Event202309GetShopWebhooksResponseDataWebhooks = void 0;
class Event202309GetShopWebhooksResponseDataWebhooks {
    static getAttributeTypeMap() {
        return Event202309GetShopWebhooksResponseDataWebhooks.attributeTypeMap;
    }
}
exports.Event202309GetShopWebhooksResponseDataWebhooks = Event202309GetShopWebhooksResponseDataWebhooks;
Event202309GetShopWebhooksResponseDataWebhooks.discriminator = undefined;
Event202309GetShopWebhooksResponseDataWebhooks.attributeTypeMap = [
    {
        "name": "address",
        "baseName": "address",
        "type": "string"
    },
    {
        "name": "createTime",
        "baseName": "create_time",
        "type": "number"
    },
    {
        "name": "eventType",
        "baseName": "event_type",
        "type": "string"
    },
    {
        "name": "updateTime",
        "baseName": "update_time",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvcFdlYmhvb2tzUmVzcG9uc2VEYXRhV2ViaG9va3MuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRTaG9wV2ViaG9va3NSZXNwb25zZURhdGFXZWJob29rcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSw4Q0FBOEM7SUEwQ3ZELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyw4Q0FBOEMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUMzRSxDQUFDOztBQTVDTCx3R0E2Q0M7QUEzQlUsNERBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLCtEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLFlBQVk7UUFDeEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9