"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Authorization202309GetAuthorizedShopsResponseData = void 0;
class Authorization202309GetAuthorizedShopsResponseData {
    static getAttributeTypeMap() {
        return Authorization202309GetAuthorizedShopsResponseData.attributeTypeMap;
    }
}
exports.Authorization202309GetAuthorizedShopsResponseData = Authorization202309GetAuthorizedShopsResponseData;
Authorization202309GetAuthorizedShopsResponseData.discriminator = undefined;
Authorization202309GetAuthorizedShopsResponseData.attributeTypeMap = [
    {
        "name": "shops",
        "baseName": "shops",
        "type": "Array<Authorization202309GetAuthorizedShopsResponseDataShops>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0QXV0aG9yaXplZFNob3BzUmVzcG9uc2VEYXRhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0QXV0aG9yaXplZFNob3BzUmVzcG9uc2VEYXRhLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLGlEQUFpRDtJQWUxRCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8saURBQWlELENBQUMsZ0JBQWdCLENBQUM7SUFDOUUsQ0FBQzs7QUFqQkwsOEdBa0JDO0FBWlUsK0RBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLGtFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxPQUFPO1FBQ2YsVUFBVSxFQUFFLE9BQU87UUFDbkIsTUFBTSxFQUFFLCtEQUErRDtLQUMxRTtDQUFLLENBQUMifQ==