"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202404OptimizedImagesRequestBodyImages = void 0;
class Product202404OptimizedImagesRequestBodyImages {
    static getAttributeTypeMap() {
        return Product202404OptimizedImagesRequestBodyImages.attributeTypeMap;
    }
}
exports.Product202404OptimizedImagesRequestBodyImages = Product202404OptimizedImagesRequestBodyImages;
Product202404OptimizedImagesRequestBodyImages.discriminator = undefined;
Product202404OptimizedImagesRequestBodyImages.attributeTypeMap = [
    {
        "name": "optimizationMode",
        "baseName": "optimization_mode",
        "type": "Array<string>"
    },
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiT3B0aW1pemVkSW1hZ2VzUmVxdWVzdEJvZHlJbWFnZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJPcHRpbWl6ZWRJbWFnZXNSZXF1ZXN0Qm9keUltYWdlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSw2Q0FBNkM7SUF3QnRELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyw2Q0FBNkMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUMxRSxDQUFDOztBQTFCTCxzR0EyQkM7QUFqQlUsMkRBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDhEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxrQkFBa0I7UUFDMUIsVUFBVSxFQUFFLG1CQUFtQjtRQUMvQixNQUFNLEVBQUUsZUFBZTtLQUMxQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLEtBQUs7UUFDYixVQUFVLEVBQUUsS0FBSztRQUNqQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==