"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches = void 0;
class Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches {
    static getAttributeTypeMap() {
        return Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches.attributeTypeMap;
    }
}
exports.Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches = Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches;
Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches.discriminator = undefined;
Fbt202409GetInboundOrderResponseDataInboundOrdersReceivedBatches.attributeTypeMap = [
    {
        "name": "defectiveQuantity",
        "baseName": "defective_quantity",
        "type": "number"
    },
    {
        "name": "goodsId",
        "baseName": "goods_id",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "normalQuantity",
        "baseName": "normal_quantity",
        "type": "number"
    },
    {
        "name": "productIds",
        "baseName": "product_ids",
        "type": "Array<string>"
    },
    {
        "name": "skuIds",
        "baseName": "sku_ids",
        "type": "Array<string>"
    },
    {
        "name": "totalQuantity",
        "baseName": "total_quantity",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0SW5ib3VuZE9yZGVyUmVzcG9uc2VEYXRhSW5ib3VuZE9yZGVyc1JlY2VpdmVkQmF0Y2hlcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldEluYm91bmRPcmRlclJlc3BvbnNlRGF0YUluYm91bmRPcmRlcnNSZWNlaXZlZEJhdGNoZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsZ0VBQWdFO0lBcUV6RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sZ0VBQWdFLENBQUMsZ0JBQWdCLENBQUM7SUFDN0YsQ0FBQzs7QUF2RUwsNElBd0VDO0FBMUNVLDhFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxpRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsbUJBQW1CO1FBQzNCLFVBQVUsRUFBRSxvQkFBb0I7UUFDaEMsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsZ0JBQWdCO1FBQ3hCLFVBQVUsRUFBRSxpQkFBaUI7UUFDN0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxlQUFlO0tBQzFCO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsU0FBUztRQUNyQixNQUFNLEVBQUUsZUFBZTtLQUMxQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==