"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fbt202409SearchGoodsInfoResponseDataGoods = void 0;
class Fbt202409SearchGoodsInfoResponseDataGoods {
    static getAttributeTypeMap() {
        return Fbt202409SearchGoodsInfoResponseDataGoods.attributeTypeMap;
    }
}
exports.Fbt202409SearchGoodsInfoResponseDataGoods = Fbt202409SearchGoodsInfoResponseDataGoods;
Fbt202409SearchGoodsInfoResponseDataGoods.discriminator = undefined;
Fbt202409SearchGoodsInfoResponseDataGoods.attributeTypeMap = [
    {
        "name": "barcodes",
        "baseName": "barcodes",
        "type": "Array<Fbt202409SearchGoodsInfoResponseDataGoodsBarcodes>"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "imageUrl",
        "baseName": "image_url",
        "type": "string"
    },
    {
        "name": "lotExpirationInfo",
        "baseName": "lot_expiration_info",
        "type": "Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfo"
    },
    {
        "name": "merchantDeclarationInfo",
        "baseName": "merchant_declaration_info",
        "type": "Fbt202409SearchGoodsInfoResponseDataGoodsMerchantDeclarationInfo"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "referenceCode",
        "baseName": "reference_code",
        "type": "string"
    },
    {
        "name": "skus",
        "baseName": "skus",
        "type": "Array<Fbt202409SearchGoodsInfoResponseDataGoodsSkus>"
    },
    {
        "name": "warehouseConfirmationInfo",
        "baseName": "warehouse_confirmation_info",
        "type": "Fbt202409SearchGoodsInfoResponseDataGoodsWarehouseConfirmationInfo"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoR29vZHNJbmZvUmVzcG9uc2VEYXRhR29vZHMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTZWFyY2hHb29kc0luZm9SZXNwb25zZURhdGFHb29kcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBU0gsTUFBYSx5Q0FBeUM7SUE4RWxELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyx5Q0FBeUMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN0RSxDQUFDOztBQWhGTCw4RkFpRkM7QUFwRFUsdURBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDBEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxVQUFVO1FBQ2xCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSwwREFBMEQ7S0FDckU7SUFDRDtRQUNJLE1BQU0sRUFBRSxJQUFJO1FBQ1osVUFBVSxFQUFFLElBQUk7UUFDaEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxVQUFVO1FBQ2xCLFVBQVUsRUFBRSxXQUFXO1FBQ3ZCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsbUJBQW1CO1FBQzNCLFVBQVUsRUFBRSxxQkFBcUI7UUFDakMsTUFBTSxFQUFFLDREQUE0RDtLQUN2RTtJQUNEO1FBQ0ksTUFBTSxFQUFFLHlCQUF5QjtRQUNqQyxVQUFVLEVBQUUsMkJBQTJCO1FBQ3ZDLE1BQU0sRUFBRSxrRUFBa0U7S0FDN0U7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxnQkFBZ0I7UUFDNUIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLHNEQUFzRDtLQUNqRTtJQUNEO1FBQ0ksTUFBTSxFQUFFLDJCQUEyQjtRQUNuQyxVQUFVLEVBQUUsNkJBQTZCO1FBQ3pDLE1BQU0sRUFBRSxvRUFBb0U7S0FDL0U7Q0FBSyxDQUFDIn0=