"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses = void 0;
class Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses {
    static getAttributeTypeMap() {
        return Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses.attributeTypeMap;
    }
}
exports.Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses = Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses;
Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses.discriminator = undefined;
Fbt202409SearchGoodsInfoResponseDataGoodsLotExpirationInfoAddresses.attributeTypeMap = [
    {
        "name": "addressLine1",
        "baseName": "address_line_1",
        "type": "string"
    },
    {
        "name": "addressLine2",
        "baseName": "address_line_2",
        "type": "string"
    },
    {
        "name": "addressLine3",
        "baseName": "address_line_3",
        "type": "string"
    },
    {
        "name": "city",
        "baseName": "city",
        "type": "string"
    },
    {
        "name": "district",
        "baseName": "district",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "phoneNumber",
        "baseName": "phone_number",
        "type": "string"
    },
    {
        "name": "postalCode",
        "baseName": "postal_code",
        "type": "string"
    },
    {
        "name": "regionCode",
        "baseName": "region_code",
        "type": "string"
    },
    {
        "name": "state",
        "baseName": "state",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoR29vZHNJbmZvUmVzcG9uc2VEYXRhR29vZHNMb3RFeHBpcmF0aW9uSW5mb0FkZHJlc3Nlcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaEdvb2RzSW5mb1Jlc3BvbnNlRGF0YUdvb2RzTG90RXhwaXJhdGlvbkluZm9BZGRyZXNzZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsbUVBQW1FO0lBZ0c1RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sbUVBQW1FLENBQUMsZ0JBQWdCLENBQUM7SUFDaEcsQ0FBQzs7QUFsR0wsa0pBbUdDO0FBekRVLGlGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxvRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsY0FBYztRQUN0QixVQUFVLEVBQUUsZ0JBQWdCO1FBQzVCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsY0FBYztRQUN0QixVQUFVLEVBQUUsZ0JBQWdCO1FBQzVCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsY0FBYztRQUN0QixVQUFVLEVBQUUsZ0JBQWdCO1FBQzVCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGFBQWE7UUFDckIsVUFBVSxFQUFFLGNBQWM7UUFDMUIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==