query FetchStores($limit: Int, $offset: Int, $sort: [String!]) {
  stores(limit: $limit, offset: $offset, sort: $sort) {
    total
    count
    offset
    results {
      id
      version
      key
      name
      nameAllLocales {
        locale
        value
      }
      languages
      countries
      distributionChannels {
        id
        key
      }
      supplyChannels {
        id
        key
      }
      custom {
        type {
          id
          key
        }
        customFieldsRaw {
          name
          value
        }
      }
    }
  }
}

