"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice = void 0;
class AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice {
    static getAttributeTypeMap() {
        return AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice.attributeTypeMap;
    }
}
exports.AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice = AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice;
AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice.discriminator = undefined;
AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice.attributeTypeMap = [
    {
        "name": "currency",
        "baseName": "currency",
        "type": "string"
    },
    {
        "name": "maximumAmount",
        "baseName": "maximum_amount",
        "type": "string"
    },
    {
        "name": "minimumAmount",
        "baseName": "minimum_amount",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0T3BlbkNvbGxhYm9yYXRpb25Qcm9kdWN0TGlzdEJ5UHJvZHVjdElkc1Jlc3BvbnNlRGF0YVByb2R1Y3RzT3JpZ2luYWxQcmljZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldE9wZW5Db2xsYWJvcmF0aW9uUHJvZHVjdExpc3RCeVByb2R1Y3RJZHNSZXNwb25zZURhdGFQcm9kdWN0c09yaWdpbmFsUHJpY2UudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsa0dBQWtHO0lBaUMzRyxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sa0dBQWtHLENBQUMsZ0JBQWdCLENBQUM7SUFDL0gsQ0FBQzs7QUFuQ0wsZ05Bb0NDO0FBdEJVLGdIQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxtSEFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==