"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop = void 0;
class AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop {
    static getAttributeTypeMap() {
        return AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop.attributeTypeMap;
    }
}
exports.AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop = AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop;
AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop.discriminator = undefined;
AffiliateCreator202509GetOpenCollaborationProductListByProductIdsResponseDataProductsShop.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0T3BlbkNvbGxhYm9yYXRpb25Qcm9kdWN0TGlzdEJ5UHJvZHVjdElkc1Jlc3BvbnNlRGF0YVByb2R1Y3RzU2hvcC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldE9wZW5Db2xsYWJvcmF0aW9uUHJvZHVjdExpc3RCeVByb2R1Y3RJZHNSZXNwb25zZURhdGFQcm9kdWN0c1Nob3AudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEseUZBQXlGO0lBZWxHLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyx5RkFBeUYsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN0SCxDQUFDOztBQWpCTCw4TEFrQkM7QUFaVSx1R0FBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsMEdBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==