"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CheckProductListingRequestBodyCertificationsImages = void 0;
class Product202309CheckProductListingRequestBodyCertificationsImages {
    static getAttributeTypeMap() {
        return Product202309CheckProductListingRequestBodyCertificationsImages.attributeTypeMap;
    }
}
exports.Product202309CheckProductListingRequestBodyCertificationsImages = Product202309CheckProductListingRequestBodyCertificationsImages;
Product202309CheckProductListingRequestBodyCertificationsImages.discriminator = undefined;
Product202309CheckProductListingRequestBodyCertificationsImages.attributeTypeMap = [
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2hlY2tQcm9kdWN0TGlzdGluZ1JlcXVlc3RCb2R5Q2VydGlmaWNhdGlvbnNJbWFnZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDaGVja1Byb2R1Y3RMaXN0aW5nUmVxdWVzdEJvZHlDZXJ0aWZpY2F0aW9uc0ltYWdlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSwrREFBK0Q7SUFleEUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLCtEQUErRCxDQUFDLGdCQUFnQixDQUFDO0lBQzVGLENBQUM7O0FBakJMLDBJQWtCQztBQVpVLDZFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxnRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsS0FBSztRQUNiLFVBQVUsRUFBRSxLQUFLO1FBQ2pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9