"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CheckProductListingRequestBodySkusPrice = void 0;
class Product202309CheckProductListingRequestBodySkusPrice {
    static getAttributeTypeMap() {
        return Product202309CheckProductListingRequestBodySkusPrice.attributeTypeMap;
    }
}
exports.Product202309CheckProductListingRequestBodySkusPrice = Product202309CheckProductListingRequestBodySkusPrice;
Product202309CheckProductListingRequestBodySkusPrice.discriminator = undefined;
Product202309CheckProductListingRequestBodySkusPrice.attributeTypeMap = [
    {
        "name": "amount",
        "baseName": "amount",
        "type": "string"
    },
    {
        "name": "currency",
        "baseName": "currency",
        "type": "string"
    },
    {
        "name": "salePrice",
        "baseName": "sale_price",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2hlY2tQcm9kdWN0TGlzdGluZ1JlcXVlc3RCb2R5U2t1c1ByaWNlLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiQ2hlY2tQcm9kdWN0TGlzdGluZ1JlcXVlc3RCb2R5U2t1c1ByaWNlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLG9EQUFvRDtJQWlDN0QsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLG9EQUFvRCxDQUFDLGdCQUFnQixDQUFDO0lBQ2pGLENBQUM7O0FBbkNMLG9IQW9DQztBQXRCVSxrRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMscUVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxVQUFVO1FBQ2xCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==