"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg = void 0;
class Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg {
    static getAttributeTypeMap() {
        return Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg.attributeTypeMap;
    }
}
exports.Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg = Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg;
Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg.discriminator = undefined;
Product202309CheckProductListingRequestBodySkusSalesAttributesSkuImg.attributeTypeMap = [
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2hlY2tQcm9kdWN0TGlzdGluZ1JlcXVlc3RCb2R5U2t1c1NhbGVzQXR0cmlidXRlc1NrdUltZy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNoZWNrUHJvZHVjdExpc3RpbmdSZXF1ZXN0Qm9keVNrdXNTYWxlc0F0dHJpYnV0ZXNTa3VJbWcudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsb0VBQW9FO0lBZTdFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxvRUFBb0UsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNqRyxDQUFDOztBQWpCTCxvSkFrQkM7QUFaVSxrRkFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMscUZBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLEtBQUs7UUFDYixVQUFVLEVBQUUsS0FBSztRQUNqQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==