"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts = void 0;
class Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts {
    static getAttributeTypeMap() {
        return Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts.attributeTypeMap;
    }
}
exports.Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts = Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts;
Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts.discriminator = undefined;
Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts.attributeTypeMap = [
    {
        "name": "text",
        "baseName": "text",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2hlY2tQcm9kdWN0TGlzdGluZ1Jlc3BvbnNlRGF0YURpYWdub3Nlc1N1Z2dlc3Rpb25zU21hcnRUZXh0cy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNoZWNrUHJvZHVjdExpc3RpbmdSZXNwb25zZURhdGFEaWFnbm9zZXNTdWdnZXN0aW9uc1NtYXJ0VGV4dHMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsMEVBQTBFO0lBZW5GLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTywwRUFBMEUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN2RyxDQUFDOztBQWpCTCxnS0FrQkM7QUFaVSx3RkFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsMkZBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==