"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CheckProductListingRequestBodyMainImages = void 0;
class Product202309CheckProductListingRequestBodyMainImages {
    static getAttributeTypeMap() {
        return Product202309CheckProductListingRequestBodyMainImages.attributeTypeMap;
    }
}
exports.Product202309CheckProductListingRequestBodyMainImages = Product202309CheckProductListingRequestBodyMainImages;
Product202309CheckProductListingRequestBodyMainImages.discriminator = undefined;
Product202309CheckProductListingRequestBodyMainImages.attributeTypeMap = [
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2hlY2tQcm9kdWN0TGlzdGluZ1JlcXVlc3RCb2R5TWFpbkltYWdlcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNoZWNrUHJvZHVjdExpc3RpbmdSZXF1ZXN0Qm9keU1haW5JbWFnZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEscURBQXFEO0lBZTlELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxxREFBcUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNsRixDQUFDOztBQWpCTCxzSEFrQkM7QUFaVSxtRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsc0VBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLEtBQUs7UUFDYixVQUFVLEVBQUUsS0FBSztRQUNqQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==