"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CheckProductListingResponseDataDiagnoses = void 0;
class Product202309CheckProductListingResponseDataDiagnoses {
    static getAttributeTypeMap() {
        return Product202309CheckProductListingResponseDataDiagnoses.attributeTypeMap;
    }
}
exports.Product202309CheckProductListingResponseDataDiagnoses = Product202309CheckProductListingResponseDataDiagnoses;
Product202309CheckProductListingResponseDataDiagnoses.discriminator = undefined;
Product202309CheckProductListingResponseDataDiagnoses.attributeTypeMap = [
    {
        "name": "diagnosisResults",
        "baseName": "diagnosis_results",
        "type": "Array<Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults>"
    },
    {
        "name": "field",
        "baseName": "field",
        "type": "string"
    },
    {
        "name": "suggestions",
        "baseName": "suggestions",
        "type": "Product202309CheckProductListingResponseDataDiagnosesSuggestions"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2hlY2tQcm9kdWN0TGlzdGluZ1Jlc3BvbnNlRGF0YURpYWdub3Nlcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNoZWNrUHJvZHVjdExpc3RpbmdSZXNwb25zZURhdGFEaWFnbm9zZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQU1ILE1BQWEscURBQXFEO0lBOEI5RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8scURBQXFELENBQUMsZ0JBQWdCLENBQUM7SUFDbEYsQ0FBQzs7QUFoQ0wsc0hBaUNDO0FBdEJVLG1FQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxzRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsa0JBQWtCO1FBQzFCLFVBQVUsRUFBRSxtQkFBbUI7UUFDL0IsTUFBTSxFQUFFLDhFQUE4RTtLQUN6RjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGFBQWE7UUFDckIsVUFBVSxFQUFFLGFBQWE7UUFDekIsTUFBTSxFQUFFLGtFQUFrRTtLQUM3RTtDQUFLLENBQUMifQ==