"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateProductRequestBodyPackageDimensions = void 0;
class Product202309CreateProductRequestBodyPackageDimensions {
    static getAttributeTypeMap() {
        return Product202309CreateProductRequestBodyPackageDimensions.attributeTypeMap;
    }
}
exports.Product202309CreateProductRequestBodyPackageDimensions = Product202309CreateProductRequestBodyPackageDimensions;
Product202309CreateProductRequestBodyPackageDimensions.discriminator = undefined;
Product202309CreateProductRequestBodyPackageDimensions.attributeTypeMap = [
    {
        "name": "height",
        "baseName": "height",
        "type": "string"
    },
    {
        "name": "length",
        "baseName": "length",
        "type": "string"
    },
    {
        "name": "unit",
        "baseName": "unit",
        "type": "string"
    },
    {
        "name": "width",
        "baseName": "width",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlUHJvZHVjdFJlcXVlc3RCb2R5UGFja2FnZURpbWVuc2lvbnMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDcmVhdGVQcm9kdWN0UmVxdWVzdEJvZHlQYWNrYWdlRGltZW5zaW9ucy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxzREFBc0Q7SUEwQy9ELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxzREFBc0QsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNuRixDQUFDOztBQTVDTCx3SEE2Q0M7QUEzQlUsb0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHVFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==