"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateProductResponseDataSkus = void 0;
class Product202309CreateProductResponseDataSkus {
    static getAttributeTypeMap() {
        return Product202309CreateProductResponseDataSkus.attributeTypeMap;
    }
}
exports.Product202309CreateProductResponseDataSkus = Product202309CreateProductResponseDataSkus;
Product202309CreateProductResponseDataSkus.discriminator = undefined;
Product202309CreateProductResponseDataSkus.attributeTypeMap = [
    {
        "name": "externalSkuId",
        "baseName": "external_sku_id",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "salesAttributes",
        "baseName": "sales_attributes",
        "type": "Array<Product202309CreateProductResponseDataSkusSalesAttributes>"
    },
    {
        "name": "sellerSku",
        "baseName": "seller_sku",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlUHJvZHVjdFJlc3BvbnNlRGF0YVNrdXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDcmVhdGVQcm9kdWN0UmVzcG9uc2VEYXRhU2t1cy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSwwQ0FBMEM7SUEwQ25ELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTywwQ0FBMEMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN2RSxDQUFDOztBQTVDTCxnR0E2Q0M7QUEzQlUsd0RBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDJEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxpQkFBaUI7UUFDN0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxJQUFJO1FBQ1osVUFBVSxFQUFFLElBQUk7UUFDaEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxpQkFBaUI7UUFDekIsVUFBVSxFQUFFLGtCQUFrQjtRQUM5QixNQUFNLEVBQUUsa0VBQWtFO0tBQzdFO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==