"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateProductRequestBodyMainImages = void 0;
class Product202309CreateProductRequestBodyMainImages {
    static getAttributeTypeMap() {
        return Product202309CreateProductRequestBodyMainImages.attributeTypeMap;
    }
}
exports.Product202309CreateProductRequestBodyMainImages = Product202309CreateProductRequestBodyMainImages;
Product202309CreateProductRequestBodyMainImages.discriminator = undefined;
Product202309CreateProductRequestBodyMainImages.attributeTypeMap = [
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlUHJvZHVjdFJlcXVlc3RCb2R5TWFpbkltYWdlcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNyZWF0ZVByb2R1Y3RSZXF1ZXN0Qm9keU1haW5JbWFnZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsK0NBQStDO0lBZXhELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTywrQ0FBK0MsQ0FBQyxnQkFBZ0IsQ0FBQztJQUM1RSxDQUFDOztBQWpCTCwwR0FrQkM7QUFaVSw2REFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsZ0VBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLEtBQUs7UUFDYixVQUFVLEVBQUUsS0FBSztRQUNqQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==