"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateGlobalProductRequestBodySizeChartTemplate = void 0;
class Product202309CreateGlobalProductRequestBodySizeChartTemplate {
    static getAttributeTypeMap() {
        return Product202309CreateGlobalProductRequestBodySizeChartTemplate.attributeTypeMap;
    }
}
exports.Product202309CreateGlobalProductRequestBodySizeChartTemplate = Product202309CreateGlobalProductRequestBodySizeChartTemplate;
Product202309CreateGlobalProductRequestBodySizeChartTemplate.discriminator = undefined;
Product202309CreateGlobalProductRequestBodySizeChartTemplate.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlR2xvYmFsUHJvZHVjdFJlcXVlc3RCb2R5U2l6ZUNoYXJ0VGVtcGxhdGUuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDcmVhdGVHbG9iYWxQcm9kdWN0UmVxdWVzdEJvZHlTaXplQ2hhcnRUZW1wbGF0ZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSw0REFBNEQ7SUFlckUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDREQUE0RCxDQUFDLGdCQUFnQixDQUFDO0lBQ3pGLENBQUM7O0FBakJMLG9JQWtCQztBQVpVLDBFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyw2RUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9