"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateProductResponseDataWarnings = void 0;
class Product202309CreateProductResponseDataWarnings {
    static getAttributeTypeMap() {
        return Product202309CreateProductResponseDataWarnings.attributeTypeMap;
    }
}
exports.Product202309CreateProductResponseDataWarnings = Product202309CreateProductResponseDataWarnings;
Product202309CreateProductResponseDataWarnings.discriminator = undefined;
Product202309CreateProductResponseDataWarnings.attributeTypeMap = [
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlUHJvZHVjdFJlc3BvbnNlRGF0YVdhcm5pbmdzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiQ3JlYXRlUHJvZHVjdFJlc3BvbnNlRGF0YVdhcm5pbmdzLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDhDQUE4QztJQWV2RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sOENBQThDLENBQUMsZ0JBQWdCLENBQUM7SUFDM0UsQ0FBQzs7QUFqQkwsd0dBa0JDO0FBWlUsNERBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLCtEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9