"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateCustomBrandsRequestBody = void 0;
class Product202309CreateCustomBrandsRequestBody {
    static getAttributeTypeMap() {
        return Product202309CreateCustomBrandsRequestBody.attributeTypeMap;
    }
}
exports.Product202309CreateCustomBrandsRequestBody = Product202309CreateCustomBrandsRequestBody;
Product202309CreateCustomBrandsRequestBody.discriminator = undefined;
Product202309CreateCustomBrandsRequestBody.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlQ3VzdG9tQnJhbmRzUmVxdWVzdEJvZHkuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDcmVhdGVDdXN0b21CcmFuZHNSZXF1ZXN0Qm9keS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSwwQ0FBMEM7SUFlbkQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDBDQUEwQyxDQUFDLGdCQUFnQixDQUFDO0lBQ3ZFLENBQUM7O0FBakJMLGdHQWtCQztBQVpVLHdEQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywyREFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9