"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309CreateCustomBrandsResponseData = void 0;
class Product202309CreateCustomBrandsResponseData {
    static getAttributeTypeMap() {
        return Product202309CreateCustomBrandsResponseData.attributeTypeMap;
    }
}
exports.Product202309CreateCustomBrandsResponseData = Product202309CreateCustomBrandsResponseData;
Product202309CreateCustomBrandsResponseData.discriminator = undefined;
Product202309CreateCustomBrandsResponseData.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlQ3VzdG9tQnJhbmRzUmVzcG9uc2VEYXRhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiQ3JlYXRlQ3VzdG9tQnJhbmRzUmVzcG9uc2VEYXRhLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDJDQUEyQztJQWVwRCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sMkNBQTJDLENBQUMsZ0JBQWdCLENBQUM7SUFDeEUsQ0FBQzs7QUFqQkwsa0dBa0JDO0FBWlUseURBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDREQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxJQUFJO1FBQ1osVUFBVSxFQUFFLElBQUk7UUFDaEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=