"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309DeleteProductsRequestBody = void 0;
class Product202309DeleteProductsRequestBody {
    static getAttributeTypeMap() {
        return Product202309DeleteProductsRequestBody.attributeTypeMap;
    }
}
exports.Product202309DeleteProductsRequestBody = Product202309DeleteProductsRequestBody;
Product202309DeleteProductsRequestBody.discriminator = undefined;
Product202309DeleteProductsRequestBody.attributeTypeMap = [
    {
        "name": "productIds",
        "baseName": "product_ids",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGVsZXRlUHJvZHVjdHNSZXF1ZXN0Qm9keS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkRlbGV0ZVByb2R1Y3RzUmVxdWVzdEJvZHkudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsc0NBQXNDO0lBZS9DLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxzQ0FBc0MsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNuRSxDQUFDOztBQWpCTCx3RkFrQkM7QUFaVSxvREFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsdURBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFlBQVk7UUFDcEIsVUFBVSxFQUFFLGFBQWE7UUFDekIsTUFBTSxFQUFFLGVBQWU7S0FDMUI7Q0FBSyxDQUFDIn0=