"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309EditProductRequestBodyProductAttributesValues = void 0;
class Product202309EditProductRequestBodyProductAttributesValues {
    static getAttributeTypeMap() {
        return Product202309EditProductRequestBodyProductAttributesValues.attributeTypeMap;
    }
}
exports.Product202309EditProductRequestBodyProductAttributesValues = Product202309EditProductRequestBodyProductAttributesValues;
Product202309EditProductRequestBodyProductAttributesValues.discriminator = undefined;
Product202309EditProductRequestBodyProductAttributesValues.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRWRpdFByb2R1Y3RSZXF1ZXN0Qm9keVByb2R1Y3RBdHRyaWJ1dGVzVmFsdWVzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiRWRpdFByb2R1Y3RSZXF1ZXN0Qm9keVByb2R1Y3RBdHRyaWJ1dGVzVmFsdWVzLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDBEQUEwRDtJQXdCbkUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDBEQUEwRCxDQUFDLGdCQUFnQixDQUFDO0lBQ3ZGLENBQUM7O0FBMUJMLGdJQTJCQztBQWpCVSx3RUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsMkVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==