"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg = void 0;
class Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg {
    static getAttributeTypeMap() {
        return Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg.attributeTypeMap;
    }
}
exports.Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg = Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg;
Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg.discriminator = undefined;
Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg.attributeTypeMap = [
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRWRpdEdsb2JhbFByb2R1Y3RSZXF1ZXN0Qm9keVNrdXNTYWxlc0F0dHJpYnV0ZXNTa3VJbWcuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJFZGl0R2xvYmFsUHJvZHVjdFJlcXVlc3RCb2R5U2t1c1NhbGVzQXR0cmlidXRlc1NrdUltZy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxrRUFBa0U7SUFlM0UsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLGtFQUFrRSxDQUFDLGdCQUFnQixDQUFDO0lBQy9GLENBQUM7O0FBakJMLGdKQWtCQztBQVpVLGdGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxtRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsS0FBSztRQUNiLFVBQVUsRUFBRSxLQUFLO1FBQ2pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9