"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309GetBrandsResponseDataBrands = void 0;
class Product202309GetBrandsResponseDataBrands {
    static getAttributeTypeMap() {
        return Product202309GetBrandsResponseDataBrands.attributeTypeMap;
    }
}
exports.Product202309GetBrandsResponseDataBrands = Product202309GetBrandsResponseDataBrands;
Product202309GetBrandsResponseDataBrands.discriminator = undefined;
Product202309GetBrandsResponseDataBrands.attributeTypeMap = [
    {
        "name": "authorizedStatus",
        "baseName": "authorized_status",
        "type": "string"
    },
    {
        "name": "brandStatus",
        "baseName": "brand_status",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "isT1Brand",
        "baseName": "is_t1_brand",
        "type": "boolean"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0QnJhbmRzUmVzcG9uc2VEYXRhQnJhbmRzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0QnJhbmRzUmVzcG9uc2VEYXRhQnJhbmRzLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLHdDQUF3QztJQW1EakQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHdDQUF3QyxDQUFDLGdCQUFnQixDQUFDO0lBQ3JFLENBQUM7O0FBckRMLDRGQXNEQztBQWhDVSxzREFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMseURBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLGtCQUFrQjtRQUMxQixVQUFVLEVBQUUsbUJBQW1CO1FBQy9CLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsYUFBYTtRQUNyQixVQUFVLEVBQUUsY0FBYztRQUMxQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLGFBQWE7UUFDekIsTUFBTSxFQUFFLFNBQVM7S0FDcEI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=