"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309GetCategoryRulesResponseDataProductCertifications = void 0;
class Product202309GetCategoryRulesResponseDataProductCertifications {
    static getAttributeTypeMap() {
        return Product202309GetCategoryRulesResponseDataProductCertifications.attributeTypeMap;
    }
}
exports.Product202309GetCategoryRulesResponseDataProductCertifications = Product202309GetCategoryRulesResponseDataProductCertifications;
Product202309GetCategoryRulesResponseDataProductCertifications.discriminator = undefined;
Product202309GetCategoryRulesResponseDataProductCertifications.attributeTypeMap = [
    {
        "name": "documentDetails",
        "baseName": "document_details",
        "type": "string"
    },
    {
        "name": "expirationDate",
        "baseName": "expiration_date",
        "type": "Product202309GetCategoryRulesResponseDataProductCertificationsExpirationDate"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "isRequired",
        "baseName": "is_required",
        "type": "boolean"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "requirementConditions",
        "baseName": "requirement_conditions",
        "type": "Array<Product202309GetCategoryRulesResponseDataProductCertificationsRequirementConditions>"
    },
    {
        "name": "sampleImageUrl",
        "baseName": "sample_image_url",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0Q2F0ZWdvcnlSdWxlc1Jlc3BvbnNlRGF0YVByb2R1Y3RDZXJ0aWZpY2F0aW9ucy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldENhdGVnb3J5UnVsZXNSZXNwb25zZURhdGFQcm9kdWN0Q2VydGlmaWNhdGlvbnMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQU1ILE1BQWEsOERBQThEO0lBa0V2RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sOERBQThELENBQUMsZ0JBQWdCLENBQUM7SUFDM0YsQ0FBQzs7QUFwRUwsd0lBcUVDO0FBMUNVLDRFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywrRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsaUJBQWlCO1FBQ3pCLFVBQVUsRUFBRSxrQkFBa0I7UUFDOUIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxnQkFBZ0I7UUFDeEIsVUFBVSxFQUFFLGlCQUFpQjtRQUM3QixNQUFNLEVBQUUsOEVBQThFO0tBQ3pGO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsU0FBUztLQUNwQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLHVCQUF1QjtRQUMvQixVQUFVLEVBQUUsd0JBQXdCO1FBQ3BDLE1BQU0sRUFBRSw0RkFBNEY7S0FDdkc7SUFDRDtRQUNJLE1BQU0sRUFBRSxnQkFBZ0I7UUFDeEIsVUFBVSxFQUFFLGtCQUFrQjtRQUM5QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==