"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309GetGlobalProductResponseDataSkusInventory = void 0;
class Product202309GetGlobalProductResponseDataSkusInventory {
    static getAttributeTypeMap() {
        return Product202309GetGlobalProductResponseDataSkusInventory.attributeTypeMap;
    }
}
exports.Product202309GetGlobalProductResponseDataSkusInventory = Product202309GetGlobalProductResponseDataSkusInventory;
Product202309GetGlobalProductResponseDataSkusInventory.discriminator = undefined;
Product202309GetGlobalProductResponseDataSkusInventory.attributeTypeMap = [
    {
        "name": "globalWarehouseId",
        "baseName": "global_warehouse_id",
        "type": "string"
    },
    {
        "name": "quantity",
        "baseName": "quantity",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0R2xvYmFsUHJvZHVjdFJlc3BvbnNlRGF0YVNrdXNJbnZlbnRvcnkuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRHbG9iYWxQcm9kdWN0UmVzcG9uc2VEYXRhU2t1c0ludmVudG9yeS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxzREFBc0Q7SUF3Qi9ELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxzREFBc0QsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNuRixDQUFDOztBQTFCTCx3SEEyQkM7QUFqQlUsb0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHVFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxtQkFBbUI7UUFDM0IsVUFBVSxFQUFFLHFCQUFxQjtRQUNqQyxNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFVBQVU7UUFDbEIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=