"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309GetGlobalProductResponseDataPackageWeight = void 0;
class Product202309GetGlobalProductResponseDataPackageWeight {
    static getAttributeTypeMap() {
        return Product202309GetGlobalProductResponseDataPackageWeight.attributeTypeMap;
    }
}
exports.Product202309GetGlobalProductResponseDataPackageWeight = Product202309GetGlobalProductResponseDataPackageWeight;
Product202309GetGlobalProductResponseDataPackageWeight.discriminator = undefined;
Product202309GetGlobalProductResponseDataPackageWeight.attributeTypeMap = [
    {
        "name": "unit",
        "baseName": "unit",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0R2xvYmFsUHJvZHVjdFJlc3BvbnNlRGF0YVBhY2thZ2VXZWlnaHQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRHbG9iYWxQcm9kdWN0UmVzcG9uc2VEYXRhUGFja2FnZVdlaWdodC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxzREFBc0Q7SUF3Qi9ELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxzREFBc0QsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNuRixDQUFDOztBQTFCTCx3SEEyQkM7QUFqQlUsb0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHVFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxPQUFPO1FBQ2YsVUFBVSxFQUFFLE9BQU87UUFDbkIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=