"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309GetProductResponseDataSkusPreSale = void 0;
class Product202309GetProductResponseDataSkusPreSale {
    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataSkusPreSale.attributeTypeMap;
    }
}
exports.Product202309GetProductResponseDataSkusPreSale = Product202309GetProductResponseDataSkusPreSale;
Product202309GetProductResponseDataSkusPreSale.discriminator = undefined;
Product202309GetProductResponseDataSkusPreSale.attributeTypeMap = [
    {
        "name": "fulfillmentType",
        "baseName": "fulfillment_type",
        "type": "Product202309GetProductResponseDataSkusPreSaleFulfillmentType"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0UHJvZHVjdFJlc3BvbnNlRGF0YVNrdXNQcmVTYWxlLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0UHJvZHVjdFJlc3BvbnNlRGF0YVNrdXNQcmVTYWxlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLDhDQUE4QztJQXFCdkQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDhDQUE4QyxDQUFDLGdCQUFnQixDQUFDO0lBQzNFLENBQUM7O0FBdkJMLHdHQXdCQztBQWpCVSw0REFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsK0RBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLGlCQUFpQjtRQUN6QixVQUFVLEVBQUUsa0JBQWtCO1FBQzlCLE1BQU0sRUFBRSwrREFBK0Q7S0FDMUU7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=