"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309GetProductResponseDataProductAttributes = void 0;
class Product202309GetProductResponseDataProductAttributes {
    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataProductAttributes.attributeTypeMap;
    }
}
exports.Product202309GetProductResponseDataProductAttributes = Product202309GetProductResponseDataProductAttributes;
Product202309GetProductResponseDataProductAttributes.discriminator = undefined;
Product202309GetProductResponseDataProductAttributes.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "values",
        "baseName": "values",
        "type": "Array<Product202309GetProductResponseDataProductAttributesValues>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0UHJvZHVjdFJlc3BvbnNlRGF0YVByb2R1Y3RBdHRyaWJ1dGVzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0UHJvZHVjdFJlc3BvbnNlRGF0YVByb2R1Y3RBdHRyaWJ1dGVzLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLG9EQUFvRDtJQWlDN0QsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLG9EQUFvRCxDQUFDLGdCQUFnQixDQUFDO0lBQ2pGLENBQUM7O0FBbkNMLG9IQW9DQztBQXRCVSxrRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMscUVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLG1FQUFtRTtLQUM5RTtDQUFLLENBQUMifQ==