"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309InventorySearchResponseData = void 0;
class Product202309InventorySearchResponseData {
    static getAttributeTypeMap() {
        return Product202309InventorySearchResponseData.attributeTypeMap;
    }
}
exports.Product202309InventorySearchResponseData = Product202309InventorySearchResponseData;
Product202309InventorySearchResponseData.discriminator = undefined;
Product202309InventorySearchResponseData.attributeTypeMap = [
    {
        "name": "inventory",
        "baseName": "inventory",
        "type": "Array<Product202309InventorySearchResponseDataInventory>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiSW52ZW50b3J5U2VhcmNoUmVzcG9uc2VEYXRhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiSW52ZW50b3J5U2VhcmNoUmVzcG9uc2VEYXRhLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLHdDQUF3QztJQWVqRCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sd0NBQXdDLENBQUMsZ0JBQWdCLENBQUM7SUFDckUsQ0FBQzs7QUFqQkwsNEZBa0JDO0FBWlUsc0RBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHlEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxXQUFXO1FBQ3ZCLE1BQU0sRUFBRSwwREFBMEQ7S0FDckU7Q0FBSyxDQUFDIn0=