"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice = void 0;
class Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice {
    static getAttributeTypeMap() {
        return Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice.attributeTypeMap;
    }
}
exports.Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice = Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice;
Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice.discriminator = undefined;
Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice.attributeTypeMap = [
    {
        "name": "amount",
        "baseName": "amount",
        "type": "string"
    },
    {
        "name": "currency",
        "baseName": "currency",
        "type": "string"
    },
    {
        "name": "salePrice",
        "baseName": "sale_price",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUHVibGlzaEdsb2JhbFByb2R1Y3RSZXF1ZXN0Qm9keVB1Ymxpc2hUYXJnZXRTa3VzUHJpY2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJQdWJsaXNoR2xvYmFsUHJvZHVjdFJlcXVlc3RCb2R5UHVibGlzaFRhcmdldFNrdXNQcmljZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxrRUFBa0U7SUFpQzNFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxrRUFBa0UsQ0FBQyxnQkFBZ0IsQ0FBQztJQUMvRixDQUFDOztBQW5DTCxnSkFvQ0M7QUF0QlUsZ0ZBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG1GQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLFlBQVk7UUFDeEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=