"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309SearchGlobalProductsResponse = void 0;
class Product202309SearchGlobalProductsResponse {
    static getAttributeTypeMap() {
        return Product202309SearchGlobalProductsResponse.attributeTypeMap;
    }
}
exports.Product202309SearchGlobalProductsResponse = Product202309SearchGlobalProductsResponse;
Product202309SearchGlobalProductsResponse.discriminator = undefined;
Product202309SearchGlobalProductsResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "Product202309SearchGlobalProductsResponseData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoR2xvYmFsUHJvZHVjdHNSZXNwb25zZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaEdsb2JhbFByb2R1Y3RzUmVzcG9uc2UudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEseUNBQXlDO0lBdUNsRCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8seUNBQXlDLENBQUMsZ0JBQWdCLENBQUM7SUFDdEUsQ0FBQzs7QUF6Q0wsOEZBMENDO0FBM0JVLHVEQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywwREFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSwrQ0FBK0M7S0FDMUQ7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==