"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309SearchProductsResponseDataProductsRecommendedCategories = void 0;
class Product202309SearchProductsResponseDataProductsRecommendedCategories {
    static getAttributeTypeMap() {
        return Product202309SearchProductsResponseDataProductsRecommendedCategories.attributeTypeMap;
    }
}
exports.Product202309SearchProductsResponseDataProductsRecommendedCategories = Product202309SearchProductsResponseDataProductsRecommendedCategories;
Product202309SearchProductsResponseDataProductsRecommendedCategories.discriminator = undefined;
Product202309SearchProductsResponseDataProductsRecommendedCategories.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "localName",
        "baseName": "local_name",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoUHJvZHVjdHNSZXNwb25zZURhdGFQcm9kdWN0c1JlY29tbWVuZGVkQ2F0ZWdvcmllcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaFByb2R1Y3RzUmVzcG9uc2VEYXRhUHJvZHVjdHNSZWNvbW1lbmRlZENhdGVnb3JpZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsb0VBQW9FO0lBd0I3RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sb0VBQW9FLENBQUMsZ0JBQWdCLENBQUM7SUFDakcsQ0FBQzs7QUExQkwsb0pBMkJDO0FBakJVLGtGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxxRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==