"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309UpdatePriceRequestBodySkus = void 0;
class Product202309UpdatePriceRequestBodySkus {
    static getAttributeTypeMap() {
        return Product202309UpdatePriceRequestBodySkus.attributeTypeMap;
    }
}
exports.Product202309UpdatePriceRequestBodySkus = Product202309UpdatePriceRequestBodySkus;
Product202309UpdatePriceRequestBodySkus.discriminator = undefined;
Product202309UpdatePriceRequestBodySkus.attributeTypeMap = [
    {
        "name": "externalListPrices",
        "baseName": "external_list_prices",
        "type": "Array<Product202309UpdatePriceRequestBodySkusExternalListPrices>"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "listPrice",
        "baseName": "list_price",
        "type": "Product202309UpdatePriceRequestBodySkusListPrice"
    },
    {
        "name": "price",
        "baseName": "price",
        "type": "Product202309UpdatePriceRequestBodySkusPrice"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVXBkYXRlUHJpY2VSZXF1ZXN0Qm9keVNrdXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJVcGRhdGVQcmljZVJlcXVlc3RCb2R5U2t1cy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBT0gsTUFBYSx1Q0FBdUM7SUFvQ2hELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyx1Q0FBdUMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNwRSxDQUFDOztBQXRDTCwwRkF1Q0M7QUEzQlUscURBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHdEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxvQkFBb0I7UUFDNUIsVUFBVSxFQUFFLHNCQUFzQjtRQUNsQyxNQUFNLEVBQUUsa0VBQWtFO0tBQzdFO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsa0RBQWtEO0tBQzdEO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsT0FBTztRQUNmLFVBQVUsRUFBRSxPQUFPO1FBQ25CLE1BQU0sRUFBRSw4Q0FBOEM7S0FDekQ7Q0FBSyxDQUFDIn0=