"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309UpdateInventoryRequestBody = void 0;
class Product202309UpdateInventoryRequestBody {
    static getAttributeTypeMap() {
        return Product202309UpdateInventoryRequestBody.attributeTypeMap;
    }
}
exports.Product202309UpdateInventoryRequestBody = Product202309UpdateInventoryRequestBody;
Product202309UpdateInventoryRequestBody.discriminator = undefined;
Product202309UpdateInventoryRequestBody.attributeTypeMap = [
    {
        "name": "skus",
        "baseName": "skus",
        "type": "Array<Product202309UpdateInventoryRequestBodySkus>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVXBkYXRlSW52ZW50b3J5UmVxdWVzdEJvZHkuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJVcGRhdGVJbnZlbnRvcnlSZXF1ZXN0Qm9keS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSx1Q0FBdUM7SUFlaEQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHVDQUF1QyxDQUFDLGdCQUFnQixDQUFDO0lBQ3BFLENBQUM7O0FBakJMLDBGQWtCQztBQVpVLHFEQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyx3REFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxvREFBb0Q7S0FDL0Q7Q0FBSyxDQUFDIn0=