"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202309UpdateInventoryResponseData = void 0;
class Product202309UpdateInventoryResponseData {
    static getAttributeTypeMap() {
        return Product202309UpdateInventoryResponseData.attributeTypeMap;
    }
}
exports.Product202309UpdateInventoryResponseData = Product202309UpdateInventoryResponseData;
Product202309UpdateInventoryResponseData.discriminator = undefined;
Product202309UpdateInventoryResponseData.attributeTypeMap = [
    {
        "name": "errors",
        "baseName": "errors",
        "type": "Array<Product202309UpdateInventoryResponseDataErrors>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVXBkYXRlSW52ZW50b3J5UmVzcG9uc2VEYXRhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiVXBkYXRlSW52ZW50b3J5UmVzcG9uc2VEYXRhLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLHdDQUF3QztJQWVqRCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sd0NBQXdDLENBQUMsZ0JBQWdCLENBQUM7SUFDckUsQ0FBQzs7QUFqQkwsNEZBa0JDO0FBWlUsc0RBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHlEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSx1REFBdUQ7S0FDbEU7Q0FBSyxDQUFDIn0=