"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Order202309GetOrderListResponseDataOrdersLineItemsItemTax = void 0;
class Order202309GetOrderListResponseDataOrdersLineItemsItemTax {
    static getAttributeTypeMap() {
        return Order202309GetOrderListResponseDataOrdersLineItemsItemTax.attributeTypeMap;
    }
}
exports.Order202309GetOrderListResponseDataOrdersLineItemsItemTax = Order202309GetOrderListResponseDataOrdersLineItemsItemTax;
Order202309GetOrderListResponseDataOrdersLineItemsItemTax.discriminator = undefined;
Order202309GetOrderListResponseDataOrdersLineItemsItemTax.attributeTypeMap = [
    {
        "name": "taxAmount",
        "baseName": "tax_amount",
        "type": "string"
    },
    {
        "name": "taxRate",
        "baseName": "tax_rate",
        "type": "string"
    },
    {
        "name": "taxType",
        "baseName": "tax_type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0T3JkZXJMaXN0UmVzcG9uc2VEYXRhT3JkZXJzTGluZUl0ZW1zSXRlbVRheC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldE9yZGVyTGlzdFJlc3BvbnNlRGF0YU9yZGVyc0xpbmVJdGVtc0l0ZW1UYXgudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEseURBQXlEO0lBaUNsRSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8seURBQXlELENBQUMsZ0JBQWdCLENBQUM7SUFDdEYsQ0FBQzs7QUFuQ0wsOEhBb0NDO0FBdEJVLHVFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywwRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFNBQVM7UUFDakIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9