"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Order202309GetOrderListResponseDataOrdersHandlingDuration = void 0;
class Order202309GetOrderListResponseDataOrdersHandlingDuration {
    static getAttributeTypeMap() {
        return Order202309GetOrderListResponseDataOrdersHandlingDuration.attributeTypeMap;
    }
}
exports.Order202309GetOrderListResponseDataOrdersHandlingDuration = Order202309GetOrderListResponseDataOrdersHandlingDuration;
Order202309GetOrderListResponseDataOrdersHandlingDuration.discriminator = undefined;
Order202309GetOrderListResponseDataOrdersHandlingDuration.attributeTypeMap = [
    {
        "name": "days",
        "baseName": "days",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0T3JkZXJMaXN0UmVzcG9uc2VEYXRhT3JkZXJzSGFuZGxpbmdEdXJhdGlvbi5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldE9yZGVyTGlzdFJlc3BvbnNlRGF0YU9yZGVyc0hhbmRsaW5nRHVyYXRpb24udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEseURBQXlEO0lBd0JsRSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8seURBQXlELENBQUMsZ0JBQWdCLENBQUM7SUFDdEYsQ0FBQzs7QUExQkwsOEhBMkJDO0FBakJVLHVFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywwRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9