"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Order202406GetExternalOrderReferencesResponseDataExternalOrders = void 0;
class Order202406GetExternalOrderReferencesResponseDataExternalOrders {
    static getAttributeTypeMap() {
        return Order202406GetExternalOrderReferencesResponseDataExternalOrders.attributeTypeMap;
    }
}
exports.Order202406GetExternalOrderReferencesResponseDataExternalOrders = Order202406GetExternalOrderReferencesResponseDataExternalOrders;
Order202406GetExternalOrderReferencesResponseDataExternalOrders.discriminator = undefined;
Order202406GetExternalOrderReferencesResponseDataExternalOrders.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "lineItems",
        "baseName": "line_items",
        "type": "Array<Order202406GetExternalOrderReferencesResponseDataExternalOrdersLineItems>"
    },
    {
        "name": "platform",
        "baseName": "platform",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0RXh0ZXJuYWxPcmRlclJlZmVyZW5jZXNSZXNwb25zZURhdGFFeHRlcm5hbE9yZGVycy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldEV4dGVybmFsT3JkZXJSZWZlcmVuY2VzUmVzcG9uc2VEYXRhRXh0ZXJuYWxPcmRlcnMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsK0RBQStEO0lBaUN4RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sK0RBQStELENBQUMsZ0JBQWdCLENBQUM7SUFDNUYsQ0FBQzs7QUFuQ0wsMElBb0NDO0FBdEJVLDZFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxnRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsaUZBQWlGO0tBQzVGO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==