"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Analytics202409GetShopVideoPerformanceDetailsResponse = void 0;
class Analytics202409GetShopVideoPerformanceDetailsResponse {
    static getAttributeTypeMap() {
        return Analytics202409GetShopVideoPerformanceDetailsResponse.attributeTypeMap;
    }
}
exports.Analytics202409GetShopVideoPerformanceDetailsResponse = Analytics202409GetShopVideoPerformanceDetailsResponse;
Analytics202409GetShopVideoPerformanceDetailsResponse.discriminator = undefined;
Analytics202409GetShopVideoPerformanceDetailsResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "Analytics202409GetShopVideoPerformanceDetailsResponseData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvcFZpZGVvUGVyZm9ybWFuY2VEZXRhaWxzUmVzcG9uc2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRTaG9wVmlkZW9QZXJmb3JtYW5jZURldGFpbHNSZXNwb25zZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxxREFBcUQ7SUF1QzlELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxxREFBcUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNsRixDQUFDOztBQXpDTCxzSEEwQ0M7QUEzQlUsbUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHNFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLDJEQUEyRDtLQUN0RTtJQUNEO1FBQ0ksTUFBTSxFQUFFLFNBQVM7UUFDakIsVUFBVSxFQUFFLFNBQVM7UUFDckIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9