"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Analytics202409GetShopVideoPerformanceListResponseDataVideos = void 0;
class Analytics202409GetShopVideoPerformanceListResponseDataVideos {
    static getAttributeTypeMap() {
        return Analytics202409GetShopVideoPerformanceListResponseDataVideos.attributeTypeMap;
    }
}
exports.Analytics202409GetShopVideoPerformanceListResponseDataVideos = Analytics202409GetShopVideoPerformanceListResponseDataVideos;
Analytics202409GetShopVideoPerformanceListResponseDataVideos.discriminator = undefined;
Analytics202409GetShopVideoPerformanceListResponseDataVideos.attributeTypeMap = [
    {
        "name": "clickThroughRate",
        "baseName": "click_through_rate",
        "type": "string"
    },
    {
        "name": "gmv",
        "baseName": "gmv",
        "type": "Analytics202409GetShopVideoPerformanceListResponseDataVideosGmv"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "products",
        "baseName": "products",
        "type": "Array<Analytics202409GetShopVideoPerformanceListResponseDataVideosProducts>"
    },
    {
        "name": "skuOrders",
        "baseName": "sku_orders",
        "type": "number"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "unitsSold",
        "baseName": "units_sold",
        "type": "number"
    },
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    },
    {
        "name": "videoPostTime",
        "baseName": "video_post_time",
        "type": "string"
    },
    {
        "name": "views",
        "baseName": "views",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvcFZpZGVvUGVyZm9ybWFuY2VMaXN0UmVzcG9uc2VEYXRhVmlkZW9zLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0U2hvcFZpZGVvUGVyZm9ybWFuY2VMaXN0UmVzcG9uc2VEYXRhVmlkZW9zLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFNSCxNQUFhLDREQUE0RDtJQTZGckUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDREQUE0RCxDQUFDLGdCQUFnQixDQUFDO0lBQ3pGLENBQUM7O0FBL0ZMLG9JQWdHQztBQXpEVSwwRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsNkVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLGtCQUFrQjtRQUMxQixVQUFVLEVBQUUsb0JBQW9CO1FBQ2hDLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsS0FBSztRQUNiLFVBQVUsRUFBRSxLQUFLO1FBQ2pCLE1BQU0sRUFBRSxpRUFBaUU7S0FDNUU7SUFDRDtRQUNJLE1BQU0sRUFBRSxJQUFJO1FBQ1osVUFBVSxFQUFFLElBQUk7UUFDaEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxVQUFVO1FBQ2xCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSw2RUFBNkU7S0FDeEY7SUFDRDtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsT0FBTztRQUNmLFVBQVUsRUFBRSxPQUFPO1FBQ25CLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFVBQVU7UUFDbEIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxpQkFBaUI7UUFDN0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxPQUFPO1FBQ2YsVUFBVSxFQUFFLE9BQU87UUFDbkIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=