"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202507ReplicateProductRequestBodyReplicateTargetSkus = void 0;
class Product202507ReplicateProductRequestBodyReplicateTargetSkus {
    static getAttributeTypeMap() {
        return Product202507ReplicateProductRequestBodyReplicateTargetSkus.attributeTypeMap;
    }
}
exports.Product202507ReplicateProductRequestBodyReplicateTargetSkus = Product202507ReplicateProductRequestBodyReplicateTargetSkus;
Product202507ReplicateProductRequestBodyReplicateTargetSkus.discriminator = undefined;
Product202507ReplicateProductRequestBodyReplicateTargetSkus.attributeTypeMap = [
    {
        "name": "inventory",
        "baseName": "inventory",
        "type": "Array<Product202507ReplicateProductRequestBodyReplicateTargetSkusInventory>"
    },
    {
        "name": "price",
        "baseName": "price",
        "type": "Product202507ReplicateProductRequestBodyReplicateTargetSkusPrice"
    },
    {
        "name": "sourceSkuId",
        "baseName": "source_sku_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUmVwbGljYXRlUHJvZHVjdFJlcXVlc3RCb2R5UmVwbGljYXRlVGFyZ2V0U2t1cy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlJlcGxpY2F0ZVByb2R1Y3RSZXF1ZXN0Qm9keVJlcGxpY2F0ZVRhcmdldFNrdXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQU1ILE1BQWEsMkRBQTJEO0lBOEJwRSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sMkRBQTJELENBQUMsZ0JBQWdCLENBQUM7SUFDeEYsQ0FBQzs7QUFoQ0wsa0lBaUNDO0FBdEJVLHlFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyw0RUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsV0FBVztRQUN2QixNQUFNLEVBQUUsNkVBQTZFO0tBQ3hGO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsT0FBTztRQUNmLFVBQVUsRUFBRSxPQUFPO1FBQ25CLE1BQU0sRUFBRSxrRUFBa0U7S0FDN0U7SUFDRDtRQUNJLE1BQU0sRUFBRSxhQUFhO1FBQ3JCLFVBQVUsRUFBRSxlQUFlO1FBQzNCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9