"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fulfillment202309BatchShipPackagesResponseDataErrorsDetail = void 0;
class Fulfillment202309BatchShipPackagesResponseDataErrorsDetail {
    static getAttributeTypeMap() {
        return Fulfillment202309BatchShipPackagesResponseDataErrorsDetail.attributeTypeMap;
    }
}
exports.Fulfillment202309BatchShipPackagesResponseDataErrorsDetail = Fulfillment202309BatchShipPackagesResponseDataErrorsDetail;
Fulfillment202309BatchShipPackagesResponseDataErrorsDetail.discriminator = undefined;
Fulfillment202309BatchShipPackagesResponseDataErrorsDetail.attributeTypeMap = [
    {
        "name": "packageId",
        "baseName": "package_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQmF0Y2hTaGlwUGFja2FnZXNSZXNwb25zZURhdGFFcnJvcnNEZXRhaWwuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJCYXRjaFNoaXBQYWNrYWdlc1Jlc3BvbnNlRGF0YUVycm9yc0RldGFpbC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSwwREFBMEQ7SUFlbkUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDBEQUEwRCxDQUFDLGdCQUFnQixDQUFDO0lBQ3ZGLENBQUM7O0FBakJMLGdJQWtCQztBQVpVLHdFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywyRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==