"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fulfillment202309BatchShipPackagesRequestBodyPackages = void 0;
class Fulfillment202309BatchShipPackagesRequestBodyPackages {
    static getAttributeTypeMap() {
        return Fulfillment202309BatchShipPackagesRequestBodyPackages.attributeTypeMap;
    }
}
exports.Fulfillment202309BatchShipPackagesRequestBodyPackages = Fulfillment202309BatchShipPackagesRequestBodyPackages;
Fulfillment202309BatchShipPackagesRequestBodyPackages.discriminator = undefined;
Fulfillment202309BatchShipPackagesRequestBodyPackages.attributeTypeMap = [
    {
        "name": "handoverMethod",
        "baseName": "handover_method",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "pickupSlot",
        "baseName": "pickup_slot",
        "type": "Fulfillment202309BatchShipPackagesRequestBodyPackagesPickupSlot"
    },
    {
        "name": "selfShipment",
        "baseName": "self_shipment",
        "type": "Fulfillment202309BatchShipPackagesRequestBodyPackagesSelfShipment"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQmF0Y2hTaGlwUGFja2FnZXNSZXF1ZXN0Qm9keVBhY2thZ2VzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiQmF0Y2hTaGlwUGFja2FnZXNSZXF1ZXN0Qm9keVBhY2thZ2VzLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFNSCxNQUFhLHFEQUFxRDtJQW9DOUQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHFEQUFxRCxDQUFDLGdCQUFnQixDQUFDO0lBQ2xGLENBQUM7O0FBdENMLHNIQXVDQztBQTNCVSxtRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsc0VBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLGdCQUFnQjtRQUN4QixVQUFVLEVBQUUsaUJBQWlCO1FBQzdCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsaUVBQWlFO0tBQzVFO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsY0FBYztRQUN0QixVQUFVLEVBQUUsZUFBZTtRQUMzQixNQUFNLEVBQUUsbUVBQW1FO0tBQzlFO0NBQUssQ0FBQyJ9