"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fulfillment202309CreatePackagesRequestBodyDimension = void 0;
class Fulfillment202309CreatePackagesRequestBodyDimension {
    static getAttributeTypeMap() {
        return Fulfillment202309CreatePackagesRequestBodyDimension.attributeTypeMap;
    }
}
exports.Fulfillment202309CreatePackagesRequestBodyDimension = Fulfillment202309CreatePackagesRequestBodyDimension;
Fulfillment202309CreatePackagesRequestBodyDimension.discriminator = undefined;
Fulfillment202309CreatePackagesRequestBodyDimension.attributeTypeMap = [
    {
        "name": "height",
        "baseName": "height",
        "type": "string"
    },
    {
        "name": "length",
        "baseName": "length",
        "type": "string"
    },
    {
        "name": "unit",
        "baseName": "unit",
        "type": "string"
    },
    {
        "name": "width",
        "baseName": "width",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRlUGFja2FnZXNSZXF1ZXN0Qm9keURpbWVuc2lvbi5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkNyZWF0ZVBhY2thZ2VzUmVxdWVzdEJvZHlEaW1lbnNpb24udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsbURBQW1EO0lBMEM1RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sbURBQW1ELENBQUMsZ0JBQWdCLENBQUM7SUFDaEYsQ0FBQzs7QUE1Q0wsa0hBNkNDO0FBM0JVLGlFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxvRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxPQUFPO1FBQ2YsVUFBVSxFQUFFLE9BQU87UUFDbkIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=