"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fulfillment202309GetTrackingResponseData = void 0;
class Fulfillment202309GetTrackingResponseData {
    static getAttributeTypeMap() {
        return Fulfillment202309GetTrackingResponseData.attributeTypeMap;
    }
}
exports.Fulfillment202309GetTrackingResponseData = Fulfillment202309GetTrackingResponseData;
Fulfillment202309GetTrackingResponseData.discriminator = undefined;
Fulfillment202309GetTrackingResponseData.attributeTypeMap = [
    {
        "name": "tracking",
        "baseName": "tracking",
        "type": "Array<Fulfillment202309GetTrackingResponseDataTracking>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0VHJhY2tpbmdSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRUcmFja2luZ1Jlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSx3Q0FBd0M7SUFlakQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHdDQUF3QyxDQUFDLGdCQUFnQixDQUFDO0lBQ3JFLENBQUM7O0FBakJMLDRGQWtCQztBQVpVLHNEQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyx5REFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUseURBQXlEO0tBQ3BFO0NBQUssQ0FBQyJ9