"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fulfillment202309SearchPackageRequestBody = void 0;
class Fulfillment202309SearchPackageRequestBody {
    static getAttributeTypeMap() {
        return Fulfillment202309SearchPackageRequestBody.attributeTypeMap;
    }
}
exports.Fulfillment202309SearchPackageRequestBody = Fulfillment202309SearchPackageRequestBody;
Fulfillment202309SearchPackageRequestBody.discriminator = undefined;
Fulfillment202309SearchPackageRequestBody.attributeTypeMap = [
    {
        "name": "createTimeGe",
        "baseName": "create_time_ge",
        "type": "number"
    },
    {
        "name": "createTimeLt",
        "baseName": "create_time_lt",
        "type": "number"
    },
    {
        "name": "packageStatus",
        "baseName": "package_status",
        "type": "string"
    },
    {
        "name": "updateTimeGe",
        "baseName": "update_time_ge",
        "type": "number"
    },
    {
        "name": "updateTimeLt",
        "baseName": "update_time_lt",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoUGFja2FnZVJlcXVlc3RCb2R5LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoUGFja2FnZVJlcXVlc3RCb2R5LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLHlDQUF5QztJQW1EbEQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHlDQUF5QyxDQUFDLGdCQUFnQixDQUFDO0lBQ3RFLENBQUM7O0FBckRMLDhGQXNEQztBQWhDVSx1REFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsMERBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==