"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fulfillment202309UncombinePackagesResponseData = void 0;
class Fulfillment202309UncombinePackagesResponseData {
    static getAttributeTypeMap() {
        return Fulfillment202309UncombinePackagesResponseData.attributeTypeMap;
    }
}
exports.Fulfillment202309UncombinePackagesResponseData = Fulfillment202309UncombinePackagesResponseData;
Fulfillment202309UncombinePackagesResponseData.discriminator = undefined;
Fulfillment202309UncombinePackagesResponseData.attributeTypeMap = [
    {
        "name": "packages",
        "baseName": "packages",
        "type": "Array<Fulfillment202309UncombinePackagesResponseDataPackages>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVW5jb21iaW5lUGFja2FnZXNSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJVbmNvbWJpbmVQYWNrYWdlc1Jlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSw4Q0FBOEM7SUFldkQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDhDQUE4QyxDQUFDLGdCQUFnQixDQUFDO0lBQzNFLENBQUM7O0FBakJMLHdHQWtCQztBQVpVLDREQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywrREFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsK0RBQStEO0tBQzFFO0NBQUssQ0FBQyJ9