"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fbt202408GetFBTWarehouseListResponseDataWarehouses = void 0;
class Fbt202408GetFBTWarehouseListResponseDataWarehouses {
    static getAttributeTypeMap() {
        return Fbt202408GetFBTWarehouseListResponseDataWarehouses.attributeTypeMap;
    }
}
exports.Fbt202408GetFBTWarehouseListResponseDataWarehouses = Fbt202408GetFBTWarehouseListResponseDataWarehouses;
Fbt202408GetFBTWarehouseListResponseDataWarehouses.discriminator = undefined;
Fbt202408GetFBTWarehouseListResponseDataWarehouses.attributeTypeMap = [
    {
        "name": "addresses",
        "baseName": "addresses",
        "type": "Array<Fbt202408GetFBTWarehouseListResponseDataWarehousesAddresses>"
    },
    {
        "name": "fbtWarehouseId",
        "baseName": "fbt_warehouse_id",
        "type": "string"
    },
    {
        "name": "logisticsServices",
        "baseName": "logistics_services",
        "type": "Array<Fbt202408GetFBTWarehouseListResponseDataWarehousesLogisticsServices>"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "subscribed",
        "baseName": "subscribed",
        "type": "boolean"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "warehouseIds",
        "baseName": "warehouse_ids",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0RkJUV2FyZWhvdXNlTGlzdFJlc3BvbnNlRGF0YVdhcmVob3VzZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRGQlRXYXJlaG91c2VMaXN0UmVzcG9uc2VEYXRhV2FyZWhvdXNlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBTUgsTUFBYSxrREFBa0Q7SUFxRTNELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxrREFBa0QsQ0FBQyxnQkFBZ0IsQ0FBQztJQUMvRSxDQUFDOztBQXZFTCxnSEF3RUM7QUExQ1UsZ0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG1FQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxXQUFXO1FBQ3ZCLE1BQU0sRUFBRSxvRUFBb0U7S0FDL0U7SUFDRDtRQUNJLE1BQU0sRUFBRSxnQkFBZ0I7UUFDeEIsVUFBVSxFQUFFLGtCQUFrQjtRQUM5QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLG1CQUFtQjtRQUMzQixVQUFVLEVBQUUsb0JBQW9CO1FBQ2hDLE1BQU0sRUFBRSw0RUFBNEU7S0FDdkY7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxTQUFTO0tBQ3BCO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsY0FBYztRQUN0QixVQUFVLEVBQUUsZUFBZTtRQUMzQixNQUFNLEVBQUUsZUFBZTtLQUMxQjtDQUFLLENBQUMifQ==