"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202405GetRecommendedProductTitleAndDescriptionResponseData = void 0;
class Product202405GetRecommendedProductTitleAndDescriptionResponseData {
    static getAttributeTypeMap() {
        return Product202405GetRecommendedProductTitleAndDescriptionResponseData.attributeTypeMap;
    }
}
exports.Product202405GetRecommendedProductTitleAndDescriptionResponseData = Product202405GetRecommendedProductTitleAndDescriptionResponseData;
Product202405GetRecommendedProductTitleAndDescriptionResponseData.discriminator = undefined;
Product202405GetRecommendedProductTitleAndDescriptionResponseData.attributeTypeMap = [
    {
        "name": "products",
        "baseName": "products",
        "type": "Array<Product202405GetRecommendedProductTitleAndDescriptionResponseDataProducts>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0UmVjb21tZW5kZWRQcm9kdWN0VGl0bGVBbmREZXNjcmlwdGlvblJlc3BvbnNlRGF0YS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldFJlY29tbWVuZGVkUHJvZHVjdFRpdGxlQW5kRGVzY3JpcHRpb25SZXNwb25zZURhdGEudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsaUVBQWlFO0lBZTFFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxpRUFBaUUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUM5RixDQUFDOztBQWpCTCw4SUFrQkM7QUFaVSwrRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsa0ZBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFVBQVU7UUFDbEIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLGtGQUFrRjtLQUM3RjtDQUFLLENBQUMifQ==