"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202405ProductInformationIssueDiagnosisResponseData = void 0;
class Product202405ProductInformationIssueDiagnosisResponseData {
    static getAttributeTypeMap() {
        return Product202405ProductInformationIssueDiagnosisResponseData.attributeTypeMap;
    }
}
exports.Product202405ProductInformationIssueDiagnosisResponseData = Product202405ProductInformationIssueDiagnosisResponseData;
Product202405ProductInformationIssueDiagnosisResponseData.discriminator = undefined;
Product202405ProductInformationIssueDiagnosisResponseData.attributeTypeMap = [
    {
        "name": "products",
        "baseName": "products",
        "type": "Array<Product202405ProductInformationIssueDiagnosisResponseDataProducts>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUHJvZHVjdEluZm9ybWF0aW9uSXNzdWVEaWFnbm9zaXNSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJQcm9kdWN0SW5mb3JtYXRpb25Jc3N1ZURpYWdub3Npc1Jlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSx5REFBeUQ7SUFlbEUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHlEQUF5RCxDQUFDLGdCQUFnQixDQUFDO0lBQ3RGLENBQUM7O0FBakJMLDhIQWtCQztBQVpVLHVFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QywwRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsMEVBQTBFO0tBQ3JGO0NBQUssQ0FBQyJ9