"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202405GetShowcaseProductsResponseData = void 0;
class AffiliateCreator202405GetShowcaseProductsResponseData {
    static getAttributeTypeMap() {
        return AffiliateCreator202405GetShowcaseProductsResponseData.attributeTypeMap;
    }
}
exports.AffiliateCreator202405GetShowcaseProductsResponseData = AffiliateCreator202405GetShowcaseProductsResponseData;
AffiliateCreator202405GetShowcaseProductsResponseData.discriminator = undefined;
AffiliateCreator202405GetShowcaseProductsResponseData.attributeTypeMap = [
    {
        "name": "nextPageToken",
        "baseName": "next_page_token",
        "type": "string"
    },
    {
        "name": "products",
        "baseName": "products",
        "type": "Array<AffiliateCreator202405GetShowcaseProductsResponseDataProducts>"
    },
    {
        "name": "totalCount",
        "baseName": "total_count",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvd2Nhc2VQcm9kdWN0c1Jlc3BvbnNlRGF0YS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldFNob3djYXNlUHJvZHVjdHNSZXNwb25zZURhdGEudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEscURBQXFEO0lBaUM5RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8scURBQXFELENBQUMsZ0JBQWdCLENBQUM7SUFDbEYsQ0FBQzs7QUFuQ0wsc0hBb0NDO0FBdEJVLG1FQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxzRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsZUFBZTtRQUN2QixVQUFVLEVBQUUsaUJBQWlCO1FBQzdCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsc0VBQXNFO0tBQ2pGO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==