"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts = void 0;
class AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts {
    static getAttributeTypeMap() {
        return AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts.attributeTypeMap;
    }
}
exports.AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts = AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts;
AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts.discriminator = undefined;
AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts.attributeTypeMap = [
    {
        "name": "commission",
        "baseName": "commission",
        "type": "AffiliateCreator202405SearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "mainImageUrl",
        "baseName": "main_image_url",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQ3JlYXRvclRhcmdldENvbGxhYm9yYXRpb25zUmVzcG9uc2VEYXRhVGFyZ2V0Q29sbGFib3JhdGlvbnNQcm9kdWN0cy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaENyZWF0b3JUYXJnZXRDb2xsYWJvcmF0aW9uc1Jlc3BvbnNlRGF0YVRhcmdldENvbGxhYm9yYXRpb25zUHJvZHVjdHMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsK0ZBQStGO0lBdUN4RyxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sK0ZBQStGLENBQUMsZ0JBQWdCLENBQUM7SUFDNUgsQ0FBQzs7QUF6Q0wsME1BMENDO0FBM0JVLDZHQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxnSEFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsMkdBQTJHO0tBQ3RIO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsY0FBYztRQUN0QixVQUFVLEVBQUUsZ0JBQWdCO1FBQzVCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsT0FBTztRQUNmLFVBQVUsRUFBRSxPQUFPO1FBQ25CLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9