"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202501SearchManufacturersResponseDataManufacturers = void 0;
class Product202501SearchManufacturersResponseDataManufacturers {
    static getAttributeTypeMap() {
        return Product202501SearchManufacturersResponseDataManufacturers.attributeTypeMap;
    }
}
exports.Product202501SearchManufacturersResponseDataManufacturers = Product202501SearchManufacturersResponseDataManufacturers;
Product202501SearchManufacturersResponseDataManufacturers.discriminator = undefined;
Product202501SearchManufacturersResponseDataManufacturers.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "regionalProfiles",
        "baseName": "regional_profiles",
        "type": "Array<Product202501SearchManufacturersResponseDataManufacturersRegionalProfiles>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoTWFudWZhY3R1cmVyc1Jlc3BvbnNlRGF0YU1hbnVmYWN0dXJlcnMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTZWFyY2hNYW51ZmFjdHVyZXJzUmVzcG9uc2VEYXRhTWFudWZhY3R1cmVycy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSx5REFBeUQ7SUF3QmxFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyx5REFBeUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN0RixDQUFDOztBQTFCTCw4SEEyQkM7QUFqQlUsdUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDBFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxJQUFJO1FBQ1osVUFBVSxFQUFFLElBQUk7UUFDaEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxrQkFBa0I7UUFDMUIsVUFBVSxFQUFFLG1CQUFtQjtRQUMvQixNQUFNLEVBQUUsa0ZBQWtGO0tBQzdGO0NBQUssQ0FBQyJ9