"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnRefund202309GetAftersaleEligibilityResponseData = void 0;
class ReturnRefund202309GetAftersaleEligibilityResponseData {
    static getAttributeTypeMap() {
        return ReturnRefund202309GetAftersaleEligibilityResponseData.attributeTypeMap;
    }
}
exports.ReturnRefund202309GetAftersaleEligibilityResponseData = ReturnRefund202309GetAftersaleEligibilityResponseData;
ReturnRefund202309GetAftersaleEligibilityResponseData.discriminator = undefined;
ReturnRefund202309GetAftersaleEligibilityResponseData.attributeTypeMap = [
    {
        "name": "skuEligibility",
        "baseName": "sku_eligibility",
        "type": "Array<ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0QWZ0ZXJzYWxlRWxpZ2liaWxpdHlSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRBZnRlcnNhbGVFbGlnaWJpbGl0eVJlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxxREFBcUQ7SUFlOUQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHFEQUFxRCxDQUFDLGdCQUFnQixDQUFDO0lBQ2xGLENBQUM7O0FBakJMLHNIQWtCQztBQVpVLG1FQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxzRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsZ0JBQWdCO1FBQ3hCLFVBQVUsRUFBRSxpQkFBaUI7UUFDN0IsTUFBTSxFQUFFLDRFQUE0RTtLQUN2RjtDQUFLLENBQUMifQ==