"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse = void 0;
class ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse {
    static getAttributeTypeMap() {
        return ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse.attributeTypeMap;
    }
}
exports.ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse = ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse;
ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse.discriminator = undefined;
ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse.attributeTypeMap = [
    {
        "name": "action",
        "baseName": "action",
        "type": "string"
    },
    {
        "name": "deadline",
        "baseName": "deadline",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQ2FuY2VsbGF0aW9uc1Jlc3BvbnNlRGF0YUNhbmNlbGxhdGlvbnNTZWxsZXJOZXh0QWN0aW9uUmVzcG9uc2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTZWFyY2hDYW5jZWxsYXRpb25zUmVzcG9uc2VEYXRhQ2FuY2VsbGF0aW9uc1NlbGxlck5leHRBY3Rpb25SZXNwb25zZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxzRkFBc0Y7SUF3Qi9GLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxzRkFBc0YsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNuSCxDQUFDOztBQTFCTCx3TEEyQkM7QUFqQlUsb0dBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHVHQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==