"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Finance202501GetTransactionsbyStatementResponseData = void 0;
class Finance202501GetTransactionsbyStatementResponseData {
    static getAttributeTypeMap() {
        return Finance202501GetTransactionsbyStatementResponseData.attributeTypeMap;
    }
}
exports.Finance202501GetTransactionsbyStatementResponseData = Finance202501GetTransactionsbyStatementResponseData;
Finance202501GetTransactionsbyStatementResponseData.discriminator = undefined;
Finance202501GetTransactionsbyStatementResponseData.attributeTypeMap = [
    {
        "name": "createTime",
        "baseName": "create_time",
        "type": "number"
    },
    {
        "name": "currency",
        "baseName": "currency",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "nextPageToken",
        "baseName": "next_page_token",
        "type": "string"
    },
    {
        "name": "payableAmount",
        "baseName": "payable_amount",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    },
    {
        "name": "totalCount",
        "baseName": "total_count",
        "type": "number"
    },
    {
        "name": "totalReserveAmount",
        "baseName": "total_reserve_amount",
        "type": "string"
    },
    {
        "name": "totalSettlementAmount",
        "baseName": "total_settlement_amount",
        "type": "string"
    },
    {
        "name": "totalSettlementBreakdown",
        "baseName": "total_settlement_breakdown",
        "type": "Finance202501GetTransactionsbyStatementResponseDataTotalSettlementBreakdown"
    },
    {
        "name": "transactions",
        "baseName": "transactions",
        "type": "Array<Finance202501GetTransactionsbyStatementResponseDataTransactions>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0VHJhbnNhY3Rpb25zYnlTdGF0ZW1lbnRSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRUcmFuc2FjdGlvbnNieVN0YXRlbWVudFJlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBTUgsTUFBYSxtREFBbUQ7SUFzRzVELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxtREFBbUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNoRixDQUFDOztBQXhHTCxrSEF5R0M7QUE5RFUsaUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG9FQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGlCQUFpQjtRQUM3QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGdCQUFnQjtRQUM1QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsb0JBQW9CO1FBQzVCLFVBQVUsRUFBRSxzQkFBc0I7UUFDbEMsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSx1QkFBdUI7UUFDL0IsVUFBVSxFQUFFLHlCQUF5QjtRQUNyQyxNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLDBCQUEwQjtRQUNsQyxVQUFVLEVBQUUsNEJBQTRCO1FBQ3hDLE1BQU0sRUFBRSw2RUFBNkU7S0FDeEY7SUFDRDtRQUNJLE1BQU0sRUFBRSxjQUFjO1FBQ3RCLFVBQVUsRUFBRSxjQUFjO1FBQzFCLE1BQU0sRUFBRSx3RUFBd0U7S0FDbkY7Q0FBSyxDQUFDIn0=