"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown = void 0;
class Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown {
    static getAttributeTypeMap() {
        return Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown.attributeTypeMap;
    }
}
exports.Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown = Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown;
Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown.discriminator = undefined;
Finance202501GetTransactionsbyStatementResponseDataTransactionsRevenueBreakdown.attributeTypeMap = [
    {
        "name": "codServiceFeeAmount",
        "baseName": "cod_service_fee_amount",
        "type": "string"
    },
    {
        "name": "refundCodServiceFeeAmount",
        "baseName": "refund_cod_service_fee_amount",
        "type": "string"
    },
    {
        "name": "refundSubtotalBeforeDiscountAmount",
        "baseName": "refund_subtotal_before_discount_amount",
        "type": "string"
    },
    {
        "name": "sellerDiscountAmount",
        "baseName": "seller_discount_amount",
        "type": "string"
    },
    {
        "name": "sellerDiscountRefundAmount",
        "baseName": "seller_discount_refund_amount",
        "type": "string"
    },
    {
        "name": "subtotalBeforeDiscountAmount",
        "baseName": "subtotal_before_discount_amount",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0VHJhbnNhY3Rpb25zYnlTdGF0ZW1lbnRSZXNwb25zZURhdGFUcmFuc2FjdGlvbnNSZXZlbnVlQnJlYWtkb3duLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0VHJhbnNhY3Rpb25zYnlTdGF0ZW1lbnRSZXNwb25zZURhdGFUcmFuc2FjdGlvbnNSZXZlbnVlQnJlYWtkb3duLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLCtFQUErRTtJQTREeEYsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLCtFQUErRSxDQUFDLGdCQUFnQixDQUFDO0lBQzVHLENBQUM7O0FBOURMLDBLQStEQztBQXJDVSw2RkFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsZ0dBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLHFCQUFxQjtRQUM3QixVQUFVLEVBQUUsd0JBQXdCO1FBQ3BDLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsMkJBQTJCO1FBQ25DLFVBQVUsRUFBRSwrQkFBK0I7UUFDM0MsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxvQ0FBb0M7UUFDNUMsVUFBVSxFQUFFLHdDQUF3QztRQUNwRCxNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLHNCQUFzQjtRQUM5QixVQUFVLEVBQUUsd0JBQXdCO1FBQ3BDLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsNEJBQTRCO1FBQ3BDLFVBQVUsRUFBRSwrQkFBK0I7UUFDM0MsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSw4QkFBOEI7UUFDdEMsVUFBVSxFQUFFLGlDQUFpQztRQUM3QyxNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==