"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns = void 0;
class Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns {
    static getAttributeTypeMap() {
        return Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns.attributeTypeMap;
    }
}
exports.Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns = Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns;
Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns.discriminator = undefined;
Analytics202405GetShopProductPerformanceResponseDataPerformanceComparisonIntervalsPageViewBreakdowns.attributeTypeMap = [
    {
        "name": "amount",
        "baseName": "amount",
        "type": "number"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvcFByb2R1Y3RQZXJmb3JtYW5jZVJlc3BvbnNlRGF0YVBlcmZvcm1hbmNlQ29tcGFyaXNvbkludGVydmFsc1BhZ2VWaWV3QnJlYWtkb3ducy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldFNob3BQcm9kdWN0UGVyZm9ybWFuY2VSZXNwb25zZURhdGFQZXJmb3JtYW5jZUNvbXBhcmlzb25JbnRlcnZhbHNQYWdlVmlld0JyZWFrZG93bnMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsb0dBQW9HO0lBd0I3RyxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sb0dBQW9HLENBQUMsZ0JBQWdCLENBQUM7SUFDakksQ0FBQzs7QUExQkwsb05BMkJDO0FBakJVLGtIQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxxSEFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==