"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202411DiagnoseandOptimizeProductRequestBodyMainImages = void 0;
class Product202411DiagnoseandOptimizeProductRequestBodyMainImages {
    static getAttributeTypeMap() {
        return Product202411DiagnoseandOptimizeProductRequestBodyMainImages.attributeTypeMap;
    }
}
exports.Product202411DiagnoseandOptimizeProductRequestBodyMainImages = Product202411DiagnoseandOptimizeProductRequestBodyMainImages;
Product202411DiagnoseandOptimizeProductRequestBodyMainImages.discriminator = undefined;
Product202411DiagnoseandOptimizeProductRequestBodyMainImages.attributeTypeMap = [
    {
        "name": "uri",
        "baseName": "uri",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGlhZ25vc2VhbmRPcHRpbWl6ZVByb2R1Y3RSZXF1ZXN0Qm9keU1haW5JbWFnZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJEaWFnbm9zZWFuZE9wdGltaXplUHJvZHVjdFJlcXVlc3RCb2R5TWFpbkltYWdlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSw0REFBNEQ7SUFlckUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDREQUE0RCxDQUFDLGdCQUFnQixDQUFDO0lBQ3pGLENBQUM7O0FBakJMLG9JQWtCQztBQVpVLDBFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyw2RUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsS0FBSztRQUNiLFVBQVUsRUFBRSxLQUFLO1FBQ2pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9