"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData = void 0;
class DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData {
    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData.attributeTypeMap;
    }
}
exports.DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData = DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData;
DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData.discriminator = undefined;
DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData.attributeTypeMap = [
    {
        "name": "errors",
        "baseName": "errors",
        "type": "Array<DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrors>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUXVhbGl0eUZhY3RvcnlPcmRlckRhdGFJbXBvcnRBUElSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJRdWFsaXR5RmFjdG9yeU9yZGVyRGF0YUltcG9ydEFQSVJlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxvRUFBb0U7SUFlN0UsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLG9FQUFvRSxDQUFDLGdCQUFnQixDQUFDO0lBQ2pHLENBQUM7O0FBakJMLG9KQWtCQztBQVpVLGtGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxxRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsbUZBQW1GO0tBQzlGO0NBQUssQ0FBQyJ9