"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody = void 0;
class DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody {
    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody.attributeTypeMap;
    }
}
exports.DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody = DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody;
DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody.discriminator = undefined;
DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody.attributeTypeMap = [
    {
        "name": "orders",
        "baseName": "orders",
        "type": "Array<DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrders>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUXVhbGl0eUZhY3RvcnlPcmRlckRhdGFJbXBvcnRBUElSZXF1ZXN0Qm9keS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlF1YWxpdHlGYWN0b3J5T3JkZXJEYXRhSW1wb3J0QVBJUmVxdWVzdEJvZHkudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsbUVBQW1FO0lBZTVFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxtRUFBbUUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNoRyxDQUFDOztBQWpCTCxrSkFrQkM7QUFaVSxpRkFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsb0ZBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLGtGQUFrRjtLQUM3RjtDQUFLLENBQUMifQ==