"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202509EditProductRequestBodySkusIdentifierCode = void 0;
class Product202509EditProductRequestBodySkusIdentifierCode {
    static getAttributeTypeMap() {
        return Product202509EditProductRequestBodySkusIdentifierCode.attributeTypeMap;
    }
}
exports.Product202509EditProductRequestBodySkusIdentifierCode = Product202509EditProductRequestBodySkusIdentifierCode;
Product202509EditProductRequestBodySkusIdentifierCode.discriminator = undefined;
Product202509EditProductRequestBodySkusIdentifierCode.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRWRpdFByb2R1Y3RSZXF1ZXN0Qm9keVNrdXNJZGVudGlmaWVyQ29kZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkVkaXRQcm9kdWN0UmVxdWVzdEJvZHlTa3VzSWRlbnRpZmllckNvZGUudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEscURBQXFEO0lBd0I5RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8scURBQXFELENBQUMsZ0JBQWdCLENBQUM7SUFDbEYsQ0FBQzs7QUExQkwsc0hBMkJDO0FBakJVLG1FQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxzRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9