"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202509EditProductRequestBodyReplicatedProducts = void 0;
class Product202509EditProductRequestBodyReplicatedProducts {
    static getAttributeTypeMap() {
        return Product202509EditProductRequestBodyReplicatedProducts.attributeTypeMap;
    }
}
exports.Product202509EditProductRequestBodyReplicatedProducts = Product202509EditProductRequestBodyReplicatedProducts;
Product202509EditProductRequestBodyReplicatedProducts.discriminator = undefined;
Product202509EditProductRequestBodyReplicatedProducts.attributeTypeMap = [
    {
        "name": "region",
        "baseName": "region",
        "type": "string"
    },
    {
        "name": "skus",
        "baseName": "skus",
        "type": "Array<Product202509EditProductRequestBodyReplicatedProductsSkus>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRWRpdFByb2R1Y3RSZXF1ZXN0Qm9keVJlcGxpY2F0ZWRQcm9kdWN0cy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkVkaXRQcm9kdWN0UmVxdWVzdEJvZHlSZXBsaWNhdGVkUHJvZHVjdHMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEscURBQXFEO0lBd0I5RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8scURBQXFELENBQUMsZ0JBQWdCLENBQUM7SUFDbEYsQ0FBQzs7QUExQkwsc0hBMkJDO0FBakJVLG1FQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxzRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsa0VBQWtFO0tBQzdFO0NBQUssQ0FBQyJ9