"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202509PartialEditProductRequestBodySizeChart = void 0;
class Product202509PartialEditProductRequestBodySizeChart {
    static getAttributeTypeMap() {
        return Product202509PartialEditProductRequestBodySizeChart.attributeTypeMap;
    }
}
exports.Product202509PartialEditProductRequestBodySizeChart = Product202509PartialEditProductRequestBodySizeChart;
Product202509PartialEditProductRequestBodySizeChart.discriminator = undefined;
Product202509PartialEditProductRequestBodySizeChart.attributeTypeMap = [
    {
        "name": "image",
        "baseName": "image",
        "type": "Product202509PartialEditProductRequestBodySizeChartImage"
    },
    {
        "name": "template",
        "baseName": "template",
        "type": "Product202509PartialEditProductRequestBodySizeChartTemplate"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUGFydGlhbEVkaXRQcm9kdWN0UmVxdWVzdEJvZHlTaXplQ2hhcnQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJQYXJ0aWFsRWRpdFByb2R1Y3RSZXF1ZXN0Qm9keVNpemVDaGFydC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBTUgsTUFBYSxtREFBbUQ7SUFrQjVELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxtREFBbUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNoRixDQUFDOztBQXBCTCxrSEFxQkM7QUFqQlUsaUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG9FQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxPQUFPO1FBQ2YsVUFBVSxFQUFFLE9BQU87UUFDbkIsTUFBTSxFQUFFLDBEQUEwRDtLQUNyRTtJQUNEO1FBQ0ksTUFBTSxFQUFFLFVBQVU7UUFDbEIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLDZEQUE2RDtLQUN4RTtDQUFLLENBQUMifQ==