"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct = void 0;
class AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct {
    static getAttributeTypeMap() {
        return AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct.attributeTypeMap;
    }
}
exports.AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct = AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct;
AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct.discriminator = undefined;
AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProduct.attributeTypeMap = [
    {
        "name": "sampleSkuList",
        "baseName": "sample_sku_list",
        "type": "Array<AffiliateCreator202412GetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuList>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0Q3JlYXRvckFwcGxpY2FibGVTYW1wbGVMYWJlbFJlc3BvbnNlRGF0YUxhYmVsU2FtcGxlUHJvZHVjdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldENyZWF0b3JBcHBsaWNhYmxlU2FtcGxlTGFiZWxSZXNwb25zZURhdGFMYWJlbFNhbXBsZVByb2R1Y3QudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsbUZBQW1GO0lBZTVGLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxtRkFBbUYsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNoSCxDQUFDOztBQWpCTCxrTEFrQkM7QUFaVSxpR0FBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsb0dBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLGVBQWU7UUFDdkIsVUFBVSxFQUFFLGlCQUFpQjtRQUM3QixNQUFNLEVBQUUseUdBQXlHO0tBQ3BIO0NBQUssQ0FBQyJ9