"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202412SearchCreatorSampleApplicationsResponse = void 0;
class AffiliateCreator202412SearchCreatorSampleApplicationsResponse {
    static getAttributeTypeMap() {
        return AffiliateCreator202412SearchCreatorSampleApplicationsResponse.attributeTypeMap;
    }
}
exports.AffiliateCreator202412SearchCreatorSampleApplicationsResponse = AffiliateCreator202412SearchCreatorSampleApplicationsResponse;
AffiliateCreator202412SearchCreatorSampleApplicationsResponse.discriminator = undefined;
AffiliateCreator202412SearchCreatorSampleApplicationsResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "AffiliateCreator202412SearchCreatorSampleApplicationsResponseData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQ3JlYXRvclNhbXBsZUFwcGxpY2F0aW9uc1Jlc3BvbnNlLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoQ3JlYXRvclNhbXBsZUFwcGxpY2F0aW9uc1Jlc3BvbnNlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLDZEQUE2RDtJQXVDdEUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDZEQUE2RCxDQUFDLGdCQUFnQixDQUFDO0lBQzFGLENBQUM7O0FBekNMLHNJQTBDQztBQTNCVSwyRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsOEVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsbUVBQW1FO0tBQzlFO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsU0FBUztRQUNqQixVQUFVLEVBQUUsU0FBUztRQUNyQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLFlBQVk7UUFDeEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=