"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope = void 0;
class Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope {
    static getAttributeTypeMap() {
        return Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope.attributeTypeMap;
    }
}
exports.Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope = Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope;
Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope.discriminator = undefined;
Promotion202309GetActivityResponseDataDiscountShippingDiscountAreaScope.attributeTypeMap = [
    {
        "name": "specificAreas",
        "baseName": "specific_areas",
        "type": "Array<string>"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0QWN0aXZpdHlSZXNwb25zZURhdGFEaXNjb3VudFNoaXBwaW5nRGlzY291bnRBcmVhU2NvcGUuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRBY3Rpdml0eVJlc3BvbnNlRGF0YURpc2NvdW50U2hpcHBpbmdEaXNjb3VudEFyZWFTY29wZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSx1RUFBdUU7SUF3QmhGLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyx1RUFBdUUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNwRyxDQUFDOztBQTFCTCwwSkEyQkM7QUFqQlUscUZBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHdGQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxnQkFBZ0I7UUFDNUIsTUFBTSxFQUFFLGVBQWU7S0FDMUI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=