"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails = void 0;
class Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails {
    static getAttributeTypeMap() {
        return Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails.attributeTypeMap;
    }
}
exports.Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails = Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails;
Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails.discriminator = undefined;
Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails.attributeTypeMap = [
    {
        "name": "thresholdType",
        "baseName": "threshold_type",
        "type": "string"
    },
    {
        "name": "thresholdValue",
        "baseName": "threshold_value",
        "type": "string"
    },
    {
        "name": "tier",
        "baseName": "tier",
        "type": "number"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0QWN0aXZpdHlSZXNwb25zZURhdGFEaXNjb3VudEJtc21EaXNjb3VudERldGFpbHMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRBY3Rpdml0eVJlc3BvbnNlRGF0YURpc2NvdW50Qm1zbURpc2NvdW50RGV0YWlscy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxpRUFBaUU7SUFtRDFFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxpRUFBaUUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUM5RixDQUFDOztBQXJETCw4SUFzREM7QUFoQ1UsK0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLGtGQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxnQkFBZ0I7UUFDNUIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxnQkFBZ0I7UUFDeEIsVUFBVSxFQUFFLGlCQUFpQjtRQUM3QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==