"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202309GetActivityResponseDataDiscountBmsmDiscount = void 0;
class Promotion202309GetActivityResponseDataDiscountBmsmDiscount {
    static getAttributeTypeMap() {
        return Promotion202309GetActivityResponseDataDiscountBmsmDiscount.attributeTypeMap;
    }
}
exports.Promotion202309GetActivityResponseDataDiscountBmsmDiscount = Promotion202309GetActivityResponseDataDiscountBmsmDiscount;
Promotion202309GetActivityResponseDataDiscountBmsmDiscount.discriminator = undefined;
Promotion202309GetActivityResponseDataDiscountBmsmDiscount.attributeTypeMap = [
    {
        "name": "details",
        "baseName": "details",
        "type": "Array<Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0QWN0aXZpdHlSZXNwb25zZURhdGFEaXNjb3VudEJtc21EaXNjb3VudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldEFjdGl2aXR5UmVzcG9uc2VEYXRhRGlzY291bnRCbXNtRGlzY291bnQudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsMERBQTBEO0lBZW5FLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTywwREFBMEQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN2RixDQUFDOztBQWpCTCxnSUFrQkM7QUFaVSx3RUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsMkVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFNBQVM7UUFDakIsVUFBVSxFQUFFLFNBQVM7UUFDckIsTUFBTSxFQUFFLDBFQUEwRTtLQUNyRjtDQUFLLENBQUMifQ==