"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202309SearchActivitiesResponseData = void 0;
class Promotion202309SearchActivitiesResponseData {
    static getAttributeTypeMap() {
        return Promotion202309SearchActivitiesResponseData.attributeTypeMap;
    }
}
exports.Promotion202309SearchActivitiesResponseData = Promotion202309SearchActivitiesResponseData;
Promotion202309SearchActivitiesResponseData.discriminator = undefined;
Promotion202309SearchActivitiesResponseData.attributeTypeMap = [
    {
        "name": "activities",
        "baseName": "activities",
        "type": "Array<Promotion202309SearchActivitiesResponseDataActivities>"
    },
    {
        "name": "nextPageToken",
        "baseName": "next_page_token",
        "type": "string"
    },
    {
        "name": "totalCount",
        "baseName": "total_count",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQWN0aXZpdGllc1Jlc3BvbnNlRGF0YS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaEFjdGl2aXRpZXNSZXNwb25zZURhdGEudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsMkNBQTJDO0lBaUNwRCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sMkNBQTJDLENBQUMsZ0JBQWdCLENBQUM7SUFDeEUsQ0FBQzs7QUFuQ0wsa0dBb0NDO0FBdEJVLHlEQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyw0REFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsOERBQThEO0tBQ3pFO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsZUFBZTtRQUN2QixVQUFVLEVBQUUsaUJBQWlCO1FBQzdCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==