"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202309SearchActivitiesResponseDataActivities = void 0;
class Promotion202309SearchActivitiesResponseDataActivities {
    static getAttributeTypeMap() {
        return Promotion202309SearchActivitiesResponseDataActivities.attributeTypeMap;
    }
}
exports.Promotion202309SearchActivitiesResponseDataActivities = Promotion202309SearchActivitiesResponseDataActivities;
Promotion202309SearchActivitiesResponseDataActivities.discriminator = undefined;
Promotion202309SearchActivitiesResponseDataActivities.attributeTypeMap = [
    {
        "name": "activityCommands",
        "baseName": "activity_commands",
        "type": "Array<string>"
    },
    {
        "name": "activityType",
        "baseName": "activity_type",
        "type": "string"
    },
    {
        "name": "beginTime",
        "baseName": "begin_time",
        "type": "number"
    },
    {
        "name": "createTime",
        "baseName": "create_time",
        "type": "number"
    },
    {
        "name": "discount",
        "baseName": "discount",
        "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscount"
    },
    {
        "name": "durationType",
        "baseName": "duration_type",
        "type": "string"
    },
    {
        "name": "endTime",
        "baseName": "end_time",
        "type": "number"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "participationLimit",
        "baseName": "participation_limit",
        "type": "Array<Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit>"
    },
    {
        "name": "productLevel",
        "baseName": "product_level",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "updateTime",
        "baseName": "update_time",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQWN0aXZpdGllc1Jlc3BvbnNlRGF0YUFjdGl2aXRpZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJTZWFyY2hBY3Rpdml0aWVzUmVzcG9uc2VEYXRhQWN0aXZpdGllcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBTUgsTUFBYSxxREFBcUQ7SUF3SDlELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxxREFBcUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNsRixDQUFDOztBQTFITCxzSEEySEM7QUF4RVUsbUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHNFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxrQkFBa0I7UUFDMUIsVUFBVSxFQUFFLG1CQUFtQjtRQUMvQixNQUFNLEVBQUUsZUFBZTtLQUMxQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGVBQWU7UUFDM0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFVBQVU7UUFDbEIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLCtEQUErRDtLQUMxRTtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGVBQWU7UUFDM0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsSUFBSTtRQUNaLFVBQVUsRUFBRSxJQUFJO1FBQ2hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsb0JBQW9CO1FBQzVCLFVBQVUsRUFBRSxxQkFBcUI7UUFDakMsTUFBTSxFQUFFLGdGQUFnRjtLQUMzRjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGVBQWU7UUFDM0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsT0FBTztRQUNmLFVBQVUsRUFBRSxPQUFPO1FBQ25CLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==