"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Affiliate202309AddShowcaseProductsoldResponseData = void 0;
class Affiliate202309AddShowcaseProductsoldResponseData {
    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldResponseData.attributeTypeMap;
    }
}
exports.Affiliate202309AddShowcaseProductsoldResponseData = Affiliate202309AddShowcaseProductsoldResponseData;
Affiliate202309AddShowcaseProductsoldResponseData.discriminator = undefined;
Affiliate202309AddShowcaseProductsoldResponseData.attributeTypeMap = [
    {
        "name": "errors",
        "baseName": "errors",
        "type": "Array<Affiliate202309AddShowcaseProductsoldResponseDataErrors>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWRkU2hvd2Nhc2VQcm9kdWN0c29sZFJlc3BvbnNlRGF0YS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkFkZFNob3djYXNlUHJvZHVjdHNvbGRSZXNwb25zZURhdGEudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsaURBQWlEO0lBZTFELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxpREFBaUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUM5RSxDQUFDOztBQWpCTCw4R0FrQkM7QUFaVSwrREFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsa0VBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLGdFQUFnRTtLQUMzRTtDQUFLLENBQUMifQ==