"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Affiliate202309GetLiveRoomInfoResponseData = void 0;
class Affiliate202309GetLiveRoomInfoResponseData {
    static getAttributeTypeMap() {
        return Affiliate202309GetLiveRoomInfoResponseData.attributeTypeMap;
    }
}
exports.Affiliate202309GetLiveRoomInfoResponseData = Affiliate202309GetLiveRoomInfoResponseData;
Affiliate202309GetLiveRoomInfoResponseData.discriminator = undefined;
Affiliate202309GetLiveRoomInfoResponseData.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "startTime",
        "baseName": "start_time",
        "type": "number"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0TGl2ZVJvb21JbmZvUmVzcG9uc2VEYXRhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0TGl2ZVJvb21JbmZvUmVzcG9uc2VEYXRhLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDBDQUEwQztJQTBDbkQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDBDQUEwQyxDQUFDLGdCQUFnQixDQUFDO0lBQ3ZFLENBQUM7O0FBNUNMLGdHQTZDQztBQTNCVSx3REFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsMkRBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLFlBQVk7UUFDeEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsT0FBTztRQUNmLFVBQVUsRUFBRSxPQUFPO1FBQ25CLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9