"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages = void 0;
class Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages {
    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages.attributeTypeMap;
    }
}
exports.Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages = Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages;
Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages.discriminator = undefined;
Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages.attributeTypeMap = [
    {
        "name": "height",
        "baseName": "height",
        "type": "number"
    },
    {
        "name": "url",
        "baseName": "url",
        "type": "string"
    },
    {
        "name": "width",
        "baseName": "width",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvd2Nhc2VQcm9kdWN0c29sZFJlc3BvbnNlRGF0YVByb2R1Y3RzTWFpbkltYWdlcy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldFNob3djYXNlUHJvZHVjdHNvbGRSZXNwb25zZURhdGFQcm9kdWN0c01haW5JbWFnZXMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsbUVBQW1FO0lBaUM1RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sbUVBQW1FLENBQUMsZ0JBQWdCLENBQUM7SUFDaEcsQ0FBQzs7QUFuQ0wsa0pBb0NDO0FBdEJVLGlGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxvRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLEtBQUs7UUFDYixVQUFVLEVBQUUsS0FBSztRQUNqQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==