"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Affiliate202309TopShowcaseProductsoldRequestBody = void 0;
class Affiliate202309TopShowcaseProductsoldRequestBody {
    static getAttributeTypeMap() {
        return Affiliate202309TopShowcaseProductsoldRequestBody.attributeTypeMap;
    }
}
exports.Affiliate202309TopShowcaseProductsoldRequestBody = Affiliate202309TopShowcaseProductsoldRequestBody;
Affiliate202309TopShowcaseProductsoldRequestBody.discriminator = undefined;
Affiliate202309TopShowcaseProductsoldRequestBody.attributeTypeMap = [
    {
        "name": "productIds",
        "baseName": "product_ids",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVG9wU2hvd2Nhc2VQcm9kdWN0c29sZFJlcXVlc3RCb2R5LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiVG9wU2hvd2Nhc2VQcm9kdWN0c29sZFJlcXVlc3RCb2R5LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLGdEQUFnRDtJQWV6RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sZ0RBQWdELENBQUMsZ0JBQWdCLENBQUM7SUFDN0UsQ0FBQzs7QUFqQkwsNEdBa0JDO0FBWlUsOERBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLGlFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxlQUFlO0tBQzFCO0NBQUssQ0FBQyJ9