"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders = void 0;
class AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders {
    static getAttributeTypeMap() {
        return AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders.attributeTypeMap;
    }
}
exports.AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders = AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders;
AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders.discriminator = undefined;
AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrders.attributeTypeMap = [
    {
        "name": "createTime",
        "baseName": "create_time",
        "type": "number"
    },
    {
        "name": "deliveryTime",
        "baseName": "delivery_time",
        "type": "number"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "skus",
        "baseName": "skus",
        "type": "Array<AffiliateCreator202410SearchCreatorAffiliateOrdersResponseDataOrdersSkus>"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQ3JlYXRvckFmZmlsaWF0ZU9yZGVyc1Jlc3BvbnNlRGF0YU9yZGVycy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaENyZWF0b3JBZmZpbGlhdGVPcmRlcnNSZXNwb25zZURhdGFPcmRlcnMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsb0VBQW9FO0lBbUQ3RSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sb0VBQW9FLENBQUMsZ0JBQWdCLENBQUM7SUFDakcsQ0FBQzs7QUFyREwsb0pBc0RDO0FBaENVLGtGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxxRkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGNBQWM7UUFDdEIsVUFBVSxFQUFFLGVBQWU7UUFDM0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxJQUFJO1FBQ1osVUFBVSxFQUFFLElBQUk7UUFDaEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLGlGQUFpRjtLQUM1RjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFFBQVE7UUFDaEIsVUFBVSxFQUFFLFFBQVE7UUFDcEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=