"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202409SearchManufacturersResponse = void 0;
class Product202409SearchManufacturersResponse {
    static getAttributeTypeMap() {
        return Product202409SearchManufacturersResponse.attributeTypeMap;
    }
}
exports.Product202409SearchManufacturersResponse = Product202409SearchManufacturersResponse;
Product202409SearchManufacturersResponse.discriminator = undefined;
Product202409SearchManufacturersResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "Product202409SearchManufacturersResponseData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoTWFudWZhY3R1cmVyc1Jlc3BvbnNlLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoTWFudWZhY3R1cmVyc1Jlc3BvbnNlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLHdDQUF3QztJQXVDakQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLHdDQUF3QyxDQUFDLGdCQUFnQixDQUFDO0lBQ3JFLENBQUM7O0FBekNMLDRGQTBDQztBQTNCVSxzREFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMseURBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsOENBQThDO0tBQ3pEO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsU0FBUztRQUNqQixVQUFVLEVBQUUsU0FBUztRQUNyQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLFlBQVk7UUFDeEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=