"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202409SearchResponsiblePersonsResponseDataResponsiblePersons = void 0;
class Product202409SearchResponsiblePersonsResponseDataResponsiblePersons {
    static getAttributeTypeMap() {
        return Product202409SearchResponsiblePersonsResponseDataResponsiblePersons.attributeTypeMap;
    }
}
exports.Product202409SearchResponsiblePersonsResponseDataResponsiblePersons = Product202409SearchResponsiblePersonsResponseDataResponsiblePersons;
Product202409SearchResponsiblePersonsResponseDataResponsiblePersons.discriminator = undefined;
Product202409SearchResponsiblePersonsResponseDataResponsiblePersons.attributeTypeMap = [
    {
        "name": "address",
        "baseName": "address",
        "type": "Product202409SearchResponsiblePersonsResponseDataResponsiblePersonsAddress"
    },
    {
        "name": "email",
        "baseName": "email",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "phoneNumber",
        "baseName": "phone_number",
        "type": "Product202409SearchResponsiblePersonsResponseDataResponsiblePersonsPhoneNumber"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoUmVzcG9uc2libGVQZXJzb25zUmVzcG9uc2VEYXRhUmVzcG9uc2libGVQZXJzb25zLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoUmVzcG9uc2libGVQZXJzb25zUmVzcG9uc2VEYXRhUmVzcG9uc2libGVQZXJzb25zLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFNSCxNQUFhLG1FQUFtRTtJQTZDNUUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLG1FQUFtRSxDQUFDLGdCQUFnQixDQUFDO0lBQ2hHLENBQUM7O0FBL0NMLGtKQWdEQztBQWhDVSxpRkFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsb0ZBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFNBQVM7UUFDakIsVUFBVSxFQUFFLFNBQVM7UUFDckIsTUFBTSxFQUFFLDRFQUE0RTtLQUN2RjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGFBQWE7UUFDckIsVUFBVSxFQUFFLGNBQWM7UUFDMUIsTUFBTSxFQUFFLGdGQUFnRjtLQUMzRjtDQUFLLENBQUMifQ==