"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202502SearchProductsResponseDataProductsSkusStatusInfo = void 0;
class Product202502SearchProductsResponseDataProductsSkusStatusInfo {
    static getAttributeTypeMap() {
        return Product202502SearchProductsResponseDataProductsSkusStatusInfo.attributeTypeMap;
    }
}
exports.Product202502SearchProductsResponseDataProductsSkusStatusInfo = Product202502SearchProductsResponseDataProductsSkusStatusInfo;
Product202502SearchProductsResponseDataProductsSkusStatusInfo.discriminator = undefined;
Product202502SearchProductsResponseDataProductsSkusStatusInfo.attributeTypeMap = [
    {
        "name": "deactivationSource",
        "baseName": "deactivation_source",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoUHJvZHVjdHNSZXNwb25zZURhdGFQcm9kdWN0c1NrdXNTdGF0dXNJbmZvLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoUHJvZHVjdHNSZXNwb25zZURhdGFQcm9kdWN0c1NrdXNTdGF0dXNJbmZvLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDZEQUE2RDtJQXdCdEUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDZEQUE2RCxDQUFDLGdCQUFnQixDQUFDO0lBQzFGLENBQUM7O0FBMUJMLHNJQTJCQztBQWpCVSwyRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsOEVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLG9CQUFvQjtRQUM1QixVQUFVLEVBQUUscUJBQXFCO1FBQ2pDLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==