"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202502SearchProductsResponseDataProductsAudit = void 0;
class Product202502SearchProductsResponseDataProductsAudit {
    static getAttributeTypeMap() {
        return Product202502SearchProductsResponseDataProductsAudit.attributeTypeMap;
    }
}
exports.Product202502SearchProductsResponseDataProductsAudit = Product202502SearchProductsResponseDataProductsAudit;
Product202502SearchProductsResponseDataProductsAudit.discriminator = undefined;
Product202502SearchProductsResponseDataProductsAudit.attributeTypeMap = [
    {
        "name": "preApprovedReasons",
        "baseName": "pre_approved_reasons",
        "type": "Array<string>"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoUHJvZHVjdHNSZXNwb25zZURhdGFQcm9kdWN0c0F1ZGl0LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoUHJvZHVjdHNSZXNwb25zZURhdGFQcm9kdWN0c0F1ZGl0LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLG9EQUFvRDtJQXdCN0QsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLG9EQUFvRCxDQUFDLGdCQUFnQixDQUFDO0lBQ2pGLENBQUM7O0FBMUJMLG9IQTJCQztBQWpCVSxrRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMscUVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLG9CQUFvQjtRQUM1QixVQUFVLEVBQUUsc0JBQXNCO1FBQ2xDLE1BQU0sRUFBRSxlQUFlO0tBQzFCO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==