"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Analytics202508GetShopLIVEPerformanceListResponseData = void 0;
class Analytics202508GetShopLIVEPerformanceListResponseData {
    static getAttributeTypeMap() {
        return Analytics202508GetShopLIVEPerformanceListResponseData.attributeTypeMap;
    }
}
exports.Analytics202508GetShopLIVEPerformanceListResponseData = Analytics202508GetShopLIVEPerformanceListResponseData;
Analytics202508GetShopLIVEPerformanceListResponseData.discriminator = undefined;
Analytics202508GetShopLIVEPerformanceListResponseData.attributeTypeMap = [
    {
        "name": "latestAvailableDate",
        "baseName": "latest_available_date",
        "type": "string"
    },
    {
        "name": "liveStreamSessions",
        "baseName": "live_stream_sessions",
        "type": "Array<Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessions>"
    },
    {
        "name": "nextPageToken",
        "baseName": "next_page_token",
        "type": "string"
    },
    {
        "name": "totalCount",
        "baseName": "total_count",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hvcExJVkVQZXJmb3JtYW5jZUxpc3RSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRTaG9wTElWRVBlcmZvcm1hbmNlTGlzdFJlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxxREFBcUQ7SUEwQzlELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxxREFBcUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNsRixDQUFDOztBQTVDTCxzSEE2Q0M7QUEzQlUsbUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHNFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxxQkFBcUI7UUFDN0IsVUFBVSxFQUFFLHVCQUF1QjtRQUNuQyxNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLG9CQUFvQjtRQUM1QixVQUFVLEVBQUUsc0JBQXNCO1FBQ2xDLE1BQU0sRUFBRSxnRkFBZ0Y7S0FDM0Y7SUFDRDtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxpQkFBaUI7UUFDN0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9