"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop = void 0;
class AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop {
    static getAttributeTypeMap() {
        return AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop.attributeTypeMap;
    }
}
exports.AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop = AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop;
AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop.discriminator = undefined;
AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsShop.attributeTypeMap = [
    {
        "name": "logoUrl",
        "baseName": "logo_url",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "rating",
        "baseName": "rating",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRvclNlbGVjdEFmZmlsaWF0ZVByb2R1Y3RSZXNwb25zZURhdGFQcm9kdWN0c1Nob3AuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDcmVhdG9yU2VsZWN0QWZmaWxpYXRlUHJvZHVjdFJlc3BvbnNlRGF0YVByb2R1Y3RzU2hvcC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSwyRUFBMkU7SUFpQ3BGLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTywyRUFBMkUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN4RyxDQUFDOztBQW5DTCxrS0FvQ0M7QUF0QlUseUZBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDRGQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==