"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock = void 0;
class AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock {
    static getAttributeTypeMap() {
        return AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock.attributeTypeMap;
    }
}
exports.AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock = AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock;
AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock.discriminator = undefined;
AffiliateCreator202501CreatorSelectAffiliateProductResponseDataProductsStock.attributeTypeMap = [
    {
        "name": "quantity",
        "baseName": "quantity",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRvclNlbGVjdEFmZmlsaWF0ZVByb2R1Y3RSZXNwb25zZURhdGFQcm9kdWN0c1N0b2NrLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiQ3JlYXRvclNlbGVjdEFmZmlsaWF0ZVByb2R1Y3RSZXNwb25zZURhdGFQcm9kdWN0c1N0b2NrLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDRFQUE0RTtJQWVyRixNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sNEVBQTRFLENBQUMsZ0JBQWdCLENBQUM7SUFDekcsQ0FBQzs7QUFqQkwsb0tBa0JDO0FBWlUsMEZBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDZGQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxVQUFVO1FBQ2xCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9