"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange = void 0;
class AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange {
    static getAttributeTypeMap() {
        return AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange.attributeTypeMap;
    }
}
exports.AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange = AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange;
AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange.discriminator = undefined;
AffiliateCreator202501CreatorSelectAffiliateProductRequestBodyFilterParamsPriceRange.attributeTypeMap = [
    {
        "name": "priceGe",
        "baseName": "price_ge",
        "type": "string"
    },
    {
        "name": "priceLe",
        "baseName": "price_le",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ3JlYXRvclNlbGVjdEFmZmlsaWF0ZVByb2R1Y3RSZXF1ZXN0Qm9keUZpbHRlclBhcmFtc1ByaWNlUmFuZ2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJDcmVhdG9yU2VsZWN0QWZmaWxpYXRlUHJvZHVjdFJlcXVlc3RCb2R5RmlsdGVyUGFyYW1zUHJpY2VSYW5nZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxvRkFBb0Y7SUF3QjdGLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxvRkFBb0YsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNqSCxDQUFDOztBQTFCTCxvTEEyQkM7QUFqQlUsa0dBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHFHQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsU0FBUztRQUNqQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==