"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Logistics202309GetGlobalSellerWarehouseResponseData = void 0;
class Logistics202309GetGlobalSellerWarehouseResponseData {
    static getAttributeTypeMap() {
        return Logistics202309GetGlobalSellerWarehouseResponseData.attributeTypeMap;
    }
}
exports.Logistics202309GetGlobalSellerWarehouseResponseData = Logistics202309GetGlobalSellerWarehouseResponseData;
Logistics202309GetGlobalSellerWarehouseResponseData.discriminator = undefined;
Logistics202309GetGlobalSellerWarehouseResponseData.attributeTypeMap = [
    {
        "name": "globalWarehouses",
        "baseName": "global_warehouses",
        "type": "Array<Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0R2xvYmFsU2VsbGVyV2FyZWhvdXNlUmVzcG9uc2VEYXRhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiR2V0R2xvYmFsU2VsbGVyV2FyZWhvdXNlUmVzcG9uc2VEYXRhLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFLSCxNQUFhLG1EQUFtRDtJQWU1RCxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sbURBQW1ELENBQUMsZ0JBQWdCLENBQUM7SUFDaEYsQ0FBQzs7QUFqQkwsa0hBa0JDO0FBWlUsaUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG9FQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxrQkFBa0I7UUFDMUIsVUFBVSxFQUFFLG1CQUFtQjtRQUMvQixNQUFNLEVBQUUsNEVBQTRFO0tBQ3ZGO0NBQUssQ0FBQyJ9