"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Logistics202309GetShippingProvidersResponseData = void 0;
class Logistics202309GetShippingProvidersResponseData {
    static getAttributeTypeMap() {
        return Logistics202309GetShippingProvidersResponseData.attributeTypeMap;
    }
}
exports.Logistics202309GetShippingProvidersResponseData = Logistics202309GetShippingProvidersResponseData;
Logistics202309GetShippingProvidersResponseData.discriminator = undefined;
Logistics202309GetShippingProvidersResponseData.attributeTypeMap = [
    {
        "name": "shippingProviders",
        "baseName": "shipping_providers",
        "type": "Array<Logistics202309GetShippingProvidersResponseDataShippingProviders>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U2hpcHBpbmdQcm92aWRlcnNSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRTaGlwcGluZ1Byb3ZpZGVyc1Jlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSwrQ0FBK0M7SUFleEQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLCtDQUErQyxDQUFDLGdCQUFnQixDQUFDO0lBQzVFLENBQUM7O0FBakJMLDBHQWtCQztBQVpVLDZEQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxnRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsbUJBQW1CO1FBQzNCLFVBQVUsRUFBRSxvQkFBb0I7UUFDaEMsTUFBTSxFQUFFLHlFQUF5RTtLQUNwRjtDQUFLLENBQUMifQ==