"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Logistics202309GetWarehouseListResponseDataWarehouses = void 0;
class Logistics202309GetWarehouseListResponseDataWarehouses {
    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseListResponseDataWarehouses.attributeTypeMap;
    }
}
exports.Logistics202309GetWarehouseListResponseDataWarehouses = Logistics202309GetWarehouseListResponseDataWarehouses;
Logistics202309GetWarehouseListResponseDataWarehouses.discriminator = undefined;
Logistics202309GetWarehouseListResponseDataWarehouses.attributeTypeMap = [
    {
        "name": "address",
        "baseName": "address",
        "type": "Logistics202309GetWarehouseListResponseDataWarehousesAddress"
    },
    {
        "name": "effectStatus",
        "baseName": "effect_status",
        "type": "string"
    },
    {
        "name": "entityId",
        "baseName": "entity_id",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "isDefault",
        "baseName": "is_default",
        "type": "boolean"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "subType",
        "baseName": "sub_type",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0V2FyZWhvdXNlTGlzdFJlc3BvbnNlRGF0YVdhcmVob3VzZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRXYXJlaG91c2VMaXN0UmVzcG9uc2VEYXRhV2FyZWhvdXNlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxxREFBcUQ7SUEyRTlELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxxREFBcUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNsRixDQUFDOztBQTdFTCxzSEE4RUM7QUEvQ1UsbUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHNFQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSw4REFBOEQ7S0FDekU7SUFDRDtRQUNJLE1BQU0sRUFBRSxjQUFjO1FBQ3RCLFVBQVUsRUFBRSxlQUFlO1FBQzNCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsV0FBVztRQUN2QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFdBQVc7UUFDbkIsVUFBVSxFQUFFLFlBQVk7UUFDeEIsTUFBTSxFQUFFLFNBQVM7S0FDcEI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9