"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202407ListingSchemasResponseDataErrorsDetail = void 0;
class Product202407ListingSchemasResponseDataErrorsDetail {
    static getAttributeTypeMap() {
        return Product202407ListingSchemasResponseDataErrorsDetail.attributeTypeMap;
    }
}
exports.Product202407ListingSchemasResponseDataErrorsDetail = Product202407ListingSchemasResponseDataErrorsDetail;
Product202407ListingSchemasResponseDataErrorsDetail.discriminator = undefined;
Product202407ListingSchemasResponseDataErrorsDetail.attributeTypeMap = [
    {
        "name": "categoryId",
        "baseName": "category_id",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTGlzdGluZ1NjaGVtYXNSZXNwb25zZURhdGFFcnJvcnNEZXRhaWwuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJMaXN0aW5nU2NoZW1hc1Jlc3BvbnNlRGF0YUVycm9yc0RldGFpbC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSxtREFBbUQ7SUFlNUQsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLG1EQUFtRCxDQUFDLGdCQUFnQixDQUFDO0lBQ2hGLENBQUM7O0FBakJMLGtIQWtCQztBQVpVLGlFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxvRUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==