"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange = void 0;
class Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange {
    static getAttributeTypeMap() {
        return Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange.attributeTypeMap;
    }
}
exports.Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange = Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange;
Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange.discriminator = undefined;
Finance202309GetPaymentsResponseDataPaymentsPaymentAmountBeforeExchange.attributeTypeMap = [
    {
        "name": "currency",
        "baseName": "currency",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0UGF5bWVudHNSZXNwb25zZURhdGFQYXltZW50c1BheW1lbnRBbW91bnRCZWZvcmVFeGNoYW5nZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldFBheW1lbnRzUmVzcG9uc2VEYXRhUGF5bWVudHNQYXltZW50QW1vdW50QmVmb3JlRXhjaGFuZ2UudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsdUVBQXVFO0lBd0JoRixNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sdUVBQXVFLENBQUMsZ0JBQWdCLENBQUM7SUFDcEcsQ0FBQzs7QUExQkwsMEpBMkJDO0FBakJVLHFGQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyx3RkFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsVUFBVTtRQUNsQixVQUFVLEVBQUUsVUFBVTtRQUN0QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==