"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Finance202309GetStatementsResponseData = void 0;
class Finance202309GetStatementsResponseData {
    static getAttributeTypeMap() {
        return Finance202309GetStatementsResponseData.attributeTypeMap;
    }
}
exports.Finance202309GetStatementsResponseData = Finance202309GetStatementsResponseData;
Finance202309GetStatementsResponseData.discriminator = undefined;
Finance202309GetStatementsResponseData.attributeTypeMap = [
    {
        "name": "nextPageToken",
        "baseName": "next_page_token",
        "type": "string"
    },
    {
        "name": "statements",
        "baseName": "statements",
        "type": "Array<Finance202309GetStatementsResponseDataStatements>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0U3RhdGVtZW50c1Jlc3BvbnNlRGF0YS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkdldFN0YXRlbWVudHNSZXNwb25zZURhdGEudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsc0NBQXNDO0lBd0IvQyxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sc0NBQXNDLENBQUMsZ0JBQWdCLENBQUM7SUFDbkUsQ0FBQzs7QUExQkwsd0ZBMkJDO0FBakJVLG9EQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyx1REFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsZUFBZTtRQUN2QixVQUFVLEVBQUUsaUJBQWlCO1FBQzdCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUseURBQXlEO0tBQ3BFO0NBQUssQ0FBQyJ9