"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Finance202309GetWithdrawalsResponseData = void 0;
class Finance202309GetWithdrawalsResponseData {
    static getAttributeTypeMap() {
        return Finance202309GetWithdrawalsResponseData.attributeTypeMap;
    }
}
exports.Finance202309GetWithdrawalsResponseData = Finance202309GetWithdrawalsResponseData;
Finance202309GetWithdrawalsResponseData.discriminator = undefined;
Finance202309GetWithdrawalsResponseData.attributeTypeMap = [
    {
        "name": "nextPageToken",
        "baseName": "next_page_token",
        "type": "string"
    },
    {
        "name": "totalCount",
        "baseName": "total_count",
        "type": "number"
    },
    {
        "name": "withdrawals",
        "baseName": "withdrawals",
        "type": "Array<Finance202309GetWithdrawalsResponseDataWithdrawals>"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0V2l0aGRyYXdhbHNSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRXaXRoZHJhd2Fsc1Jlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSx1Q0FBdUM7SUFpQ2hELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyx1Q0FBdUMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNwRSxDQUFDOztBQW5DTCwwRkFvQ0M7QUF0QlUscURBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLHdEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLFVBQVUsRUFBRSxpQkFBaUI7UUFDN0IsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxhQUFhO1FBQ3pCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsYUFBYTtRQUNyQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsMkRBQTJEO0tBQ3RFO0NBQUssQ0FBQyJ9