"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product202312SearchGlobalProductsResponseDataGlobalProducts = void 0;
class Product202312SearchGlobalProductsResponseDataGlobalProducts {
    static getAttributeTypeMap() {
        return Product202312SearchGlobalProductsResponseDataGlobalProducts.attributeTypeMap;
    }
}
exports.Product202312SearchGlobalProductsResponseDataGlobalProducts = Product202312SearchGlobalProductsResponseDataGlobalProducts;
Product202312SearchGlobalProductsResponseDataGlobalProducts.discriminator = undefined;
Product202312SearchGlobalProductsResponseDataGlobalProducts.attributeTypeMap = [
    {
        "name": "createTime",
        "baseName": "create_time",
        "type": "number"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "skus",
        "baseName": "skus",
        "type": "Array<Product202312SearchGlobalProductsResponseDataGlobalProductsSkus>"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "updateTime",
        "baseName": "update_time",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoR2xvYmFsUHJvZHVjdHNSZXNwb25zZURhdGFHbG9iYWxQcm9kdWN0cy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlNlYXJjaEdsb2JhbFByb2R1Y3RzUmVzcG9uc2VEYXRhR2xvYmFsUHJvZHVjdHMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsMkRBQTJEO0lBNERwRSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sMkRBQTJELENBQUMsZ0JBQWdCLENBQUM7SUFDeEYsQ0FBQzs7QUE5REwsa0lBK0RDO0FBckNVLHlFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyw0RUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLElBQUk7UUFDWixVQUFVLEVBQUUsSUFBSTtRQUNoQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsd0VBQXdFO0tBQ25GO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsUUFBUTtRQUNoQixVQUFVLEVBQUUsUUFBUTtRQUNwQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLE9BQU87UUFDZixVQUFVLEVBQUUsT0FBTztRQUNuQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFlBQVk7UUFDcEIsVUFBVSxFQUFFLGFBQWE7UUFDekIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7Q0FBSyxDQUFDIn0=