"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataReconciliation202309OrderStatusDataExchangeResponseDataErrors = void 0;
class DataReconciliation202309OrderStatusDataExchangeResponseDataErrors {
    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponseDataErrors.attributeTypeMap;
    }
}
exports.DataReconciliation202309OrderStatusDataExchangeResponseDataErrors = DataReconciliation202309OrderStatusDataExchangeResponseDataErrors;
DataReconciliation202309OrderStatusDataExchangeResponseDataErrors.discriminator = undefined;
DataReconciliation202309OrderStatusDataExchangeResponseDataErrors.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "detail",
        "baseName": "detail",
        "type": "DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetail"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiT3JkZXJTdGF0dXNEYXRhRXhjaGFuZ2VSZXNwb25zZURhdGFFcnJvcnMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJPcmRlclN0YXR1c0RhdGFFeGNoYW5nZVJlc3BvbnNlRGF0YUVycm9ycy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxpRUFBaUU7SUE4QjFFLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxpRUFBaUUsQ0FBQyxnQkFBZ0IsQ0FBQztJQUM5RixDQUFDOztBQWhDTCw4SUFpQ0M7QUF0QlUsK0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLGtGQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSx5RUFBeUU7S0FDcEY7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9