"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors = void 0;
class DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors {
    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors.attributeTypeMap;
    }
}
exports.DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors = DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors;
DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors.discriminator = undefined;
DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "string"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiT3JkZXJTdGF0dXNEYXRhRXhjaGFuZ2VSZXNwb25zZURhdGFFcnJvcnNEZXRhaWxFeHRyYUVycm9ycy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIk9yZGVyU3RhdHVzRGF0YUV4Y2hhbmdlUmVzcG9uc2VEYXRhRXJyb3JzRGV0YWlsRXh0cmFFcnJvcnMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUlILE1BQWEsa0ZBQWtGO0lBd0IzRixNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sa0ZBQWtGLENBQUMsZ0JBQWdCLENBQUM7SUFDL0csQ0FBQzs7QUExQkwsZ0xBMkJDO0FBakJVLGdHQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5QyxtR0FBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsU0FBUztRQUNqQixVQUFVLEVBQUUsU0FBUztRQUNyQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==