"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataReconciliation202309OrderStatusDataExchangeResponse = void 0;
class DataReconciliation202309OrderStatusDataExchangeResponse {
    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponse.attributeTypeMap;
    }
}
exports.DataReconciliation202309OrderStatusDataExchangeResponse = DataReconciliation202309OrderStatusDataExchangeResponse;
DataReconciliation202309OrderStatusDataExchangeResponse.discriminator = undefined;
DataReconciliation202309OrderStatusDataExchangeResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "DataReconciliation202309OrderStatusDataExchangeResponseData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiT3JkZXJTdGF0dXNEYXRhRXhjaGFuZ2VSZXNwb25zZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIk9yZGVyU3RhdHVzRGF0YUV4Y2hhbmdlUmVzcG9uc2UudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUc7OztBQUtILE1BQWEsdURBQXVEO0lBdUNoRSxNQUFNLENBQUMsbUJBQW1CO1FBQ3RCLE9BQU8sdURBQXVELENBQUMsZ0JBQWdCLENBQUM7SUFDcEYsQ0FBQzs7QUF6Q0wsMEhBMENDO0FBM0JVLHFFQUFhLEdBQXVCLFNBQVMsQ0FBQztBQUU5Qyx3RUFBZ0IsR0FBMEQ7SUFDN0U7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsTUFBTTtRQUNkLFVBQVUsRUFBRSxNQUFNO1FBQ2xCLE1BQU0sRUFBRSw2REFBNkQ7S0FDeEU7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==