"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202406GetCouponResponseDataCouponDiscount = void 0;
class Promotion202406GetCouponResponseDataCouponDiscount {
    static getAttributeTypeMap() {
        return Promotion202406GetCouponResponseDataCouponDiscount.attributeTypeMap;
    }
}
exports.Promotion202406GetCouponResponseDataCouponDiscount = Promotion202406GetCouponResponseDataCouponDiscount;
Promotion202406GetCouponResponseDataCouponDiscount.discriminator = undefined;
Promotion202406GetCouponResponseDataCouponDiscount.attributeTypeMap = [
    {
        "name": "maxDiscount",
        "baseName": "max_discount",
        "type": "Promotion202406GetCouponResponseDataCouponDiscountMaxDiscount"
    },
    {
        "name": "percentage",
        "baseName": "percentage",
        "type": "string"
    },
    {
        "name": "reductionAmount",
        "baseName": "reduction_amount",
        "type": "Promotion202406GetCouponResponseDataCouponDiscountReductionAmount"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0Q291cG9uUmVzcG9uc2VEYXRhQ291cG9uRGlzY291bnQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRDb3Vwb25SZXNwb25zZURhdGFDb3Vwb25EaXNjb3VudC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBTUgsTUFBYSxrREFBa0Q7SUFvQzNELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxrREFBa0QsQ0FBQyxnQkFBZ0IsQ0FBQztJQUMvRSxDQUFDOztBQXRDTCxnSEF1Q0M7QUEzQlUsZ0VBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG1FQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxhQUFhO1FBQ3JCLFVBQVUsRUFBRSxjQUFjO1FBQzFCLE1BQU0sRUFBRSwrREFBK0Q7S0FDMUU7SUFDRDtRQUNJLE1BQU0sRUFBRSxZQUFZO1FBQ3BCLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsaUJBQWlCO1FBQ3pCLFVBQVUsRUFBRSxrQkFBa0I7UUFDOUIsTUFBTSxFQUFFLG1FQUFtRTtLQUM5RTtJQUNEO1FBQ0ksTUFBTSxFQUFFLE1BQU07UUFDZCxVQUFVLEVBQUUsTUFBTTtRQUNsQixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==