"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202406GetCouponResponse = void 0;
class Promotion202406GetCouponResponse {
    static getAttributeTypeMap() {
        return Promotion202406GetCouponResponse.attributeTypeMap;
    }
}
exports.Promotion202406GetCouponResponse = Promotion202406GetCouponResponse;
Promotion202406GetCouponResponse.discriminator = undefined;
Promotion202406GetCouponResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "Promotion202406GetCouponResponseData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0Q291cG9uUmVzcG9uc2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRDb3Vwb25SZXNwb25zZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxnQ0FBZ0M7SUF1Q3pDLE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxnQ0FBZ0MsQ0FBQyxnQkFBZ0IsQ0FBQztJQUM3RCxDQUFDOztBQXpDTCw0RUEwQ0M7QUEzQlUsOENBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLGlEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLHNDQUFzQztLQUNqRDtJQUNEO1FBQ0ksTUFBTSxFQUFFLFNBQVM7UUFDakIsVUFBVSxFQUFFLFNBQVM7UUFDckIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9