"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Promotion202406SearchCouponsResponseDataCouponsClaimDuration = void 0;
class Promotion202406SearchCouponsResponseDataCouponsClaimDuration {
    static getAttributeTypeMap() {
        return Promotion202406SearchCouponsResponseDataCouponsClaimDuration.attributeTypeMap;
    }
}
exports.Promotion202406SearchCouponsResponseDataCouponsClaimDuration = Promotion202406SearchCouponsResponseDataCouponsClaimDuration;
Promotion202406SearchCouponsResponseDataCouponsClaimDuration.discriminator = undefined;
Promotion202406SearchCouponsResponseDataCouponsClaimDuration.attributeTypeMap = [
    {
        "name": "endTime",
        "baseName": "end_time",
        "type": "number"
    },
    {
        "name": "startTime",
        "baseName": "start_time",
        "type": "number"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2VhcmNoQ291cG9uc1Jlc3BvbnNlRGF0YUNvdXBvbnNDbGFpbUR1cmF0aW9uLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU2VhcmNoQ291cG9uc1Jlc3BvbnNlRGF0YUNvdXBvbnNDbGFpbUR1cmF0aW9uLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHOzs7QUFJSCxNQUFhLDREQUE0RDtJQXdCckUsTUFBTSxDQUFDLG1CQUFtQjtRQUN0QixPQUFPLDREQUE0RCxDQUFDLGdCQUFnQixDQUFDO0lBQ3pGLENBQUM7O0FBMUJMLG9JQTJCQztBQWpCVSwwRUFBYSxHQUF1QixTQUFTLENBQUM7QUFFOUMsNkVBQWdCLEdBQTBEO0lBQzdFO1FBQ0ksTUFBTSxFQUFFLFNBQVM7UUFDakIsVUFBVSxFQUFFLFVBQVU7UUFDdEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxXQUFXO1FBQ25CLFVBQVUsRUFBRSxZQUFZO1FBQ3hCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9