"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Authorization202403DeauthorizeShopResponse = void 0;
class Authorization202403DeauthorizeShopResponse {
    static getAttributeTypeMap() {
        return Authorization202403DeauthorizeShopResponse.attributeTypeMap;
    }
}
exports.Authorization202403DeauthorizeShopResponse = Authorization202403DeauthorizeShopResponse;
Authorization202403DeauthorizeShopResponse.discriminator = undefined;
Authorization202403DeauthorizeShopResponse.attributeTypeMap = [
    {
        "name": "code",
        "baseName": "code",
        "type": "number"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "object"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "requestId",
        "baseName": "request_id",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGVhdXRob3JpemVTaG9wUmVzcG9uc2UuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJEZWF1dGhvcml6ZVNob3BSZXNwb25zZS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBSUgsTUFBYSwwQ0FBMEM7SUF1Q25ELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTywwQ0FBMEMsQ0FBQyxnQkFBZ0IsQ0FBQztJQUN2RSxDQUFDOztBQXpDTCxnR0EwQ0M7QUEzQlUsd0RBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLDJEQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxNQUFNO1FBQ2QsVUFBVSxFQUFFLE1BQU07UUFDbEIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxTQUFTO1FBQ2pCLFVBQVUsRUFBRSxTQUFTO1FBQ3JCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsV0FBVztRQUNuQixVQUFVLEVBQUUsWUFBWTtRQUN4QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtDQUFLLENBQUMifQ==