"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffiliateCreator202508GetCreatorProfileResponseData = void 0;
class AffiliateCreator202508GetCreatorProfileResponseData {
    static getAttributeTypeMap() {
        return AffiliateCreator202508GetCreatorProfileResponseData.attributeTypeMap;
    }
}
exports.AffiliateCreator202508GetCreatorProfileResponseData = AffiliateCreator202508GetCreatorProfileResponseData;
AffiliateCreator202508GetCreatorProfileResponseData.discriminator = undefined;
AffiliateCreator202508GetCreatorProfileResponseData.attributeTypeMap = [
    {
        "name": "avatar",
        "baseName": "avatar",
        "type": "AffiliateCreator202508GetCreatorProfileResponseDataAvatar"
    },
    {
        "name": "creatorUserOpenId",
        "baseName": "creator_user_open_id",
        "type": "string"
    },
    {
        "name": "permissions",
        "baseName": "permissions",
        "type": "Array<string>"
    },
    {
        "name": "registerRegion",
        "baseName": "register_region",
        "type": "string"
    },
    {
        "name": "selectionRegion",
        "baseName": "selection_region",
        "type": "string"
    },
    {
        "name": "sellerType",
        "baseName": "seller_type",
        "type": "string"
    },
    {
        "name": "userType",
        "baseName": "user_type",
        "type": "string"
    },
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2V0Q3JlYXRvclByb2ZpbGVSZXNwb25zZURhdGEuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJHZXRDcmVhdG9yUHJvZmlsZVJlc3BvbnNlRGF0YS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRzs7O0FBS0gsTUFBYSxtREFBbUQ7SUEyRTVELE1BQU0sQ0FBQyxtQkFBbUI7UUFDdEIsT0FBTyxtREFBbUQsQ0FBQyxnQkFBZ0IsQ0FBQztJQUNoRixDQUFDOztBQTdFTCxrSEE4RUM7QUEvQ1UsaUVBQWEsR0FBdUIsU0FBUyxDQUFDO0FBRTlDLG9FQUFnQixHQUEwRDtJQUM3RTtRQUNJLE1BQU0sRUFBRSxRQUFRO1FBQ2hCLFVBQVUsRUFBRSxRQUFRO1FBQ3BCLE1BQU0sRUFBRSwyREFBMkQ7S0FDdEU7SUFDRDtRQUNJLE1BQU0sRUFBRSxtQkFBbUI7UUFDM0IsVUFBVSxFQUFFLHNCQUFzQjtRQUNsQyxNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGFBQWE7UUFDckIsVUFBVSxFQUFFLGFBQWE7UUFDekIsTUFBTSxFQUFFLGVBQWU7S0FDMUI7SUFDRDtRQUNJLE1BQU0sRUFBRSxnQkFBZ0I7UUFDeEIsVUFBVSxFQUFFLGlCQUFpQjtRQUM3QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLGlCQUFpQjtRQUN6QixVQUFVLEVBQUUsa0JBQWtCO1FBQzlCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0lBQ0Q7UUFDSSxNQUFNLEVBQUUsWUFBWTtRQUNwQixVQUFVLEVBQUUsYUFBYTtRQUN6QixNQUFNLEVBQUUsUUFBUTtLQUNuQjtJQUNEO1FBQ0ksTUFBTSxFQUFFLFVBQVU7UUFDbEIsVUFBVSxFQUFFLFdBQVc7UUFDdkIsTUFBTSxFQUFFLFFBQVE7S0FDbkI7SUFDRDtRQUNJLE1BQU0sRUFBRSxVQUFVO1FBQ2xCLFVBQVUsRUFBRSxVQUFVO1FBQ3RCLE1BQU0sRUFBRSxRQUFRO0tBQ25CO0NBQUssQ0FBQyJ9